
{{config(
  materialized='ephemeral'
)}}

WITH lkp_cl_v AS (
SELECT
            		TRF_IFL_TGT.REL_END_DATE AS TRF_IFL_TGT_REL_END_DATE,
            	TRF_IFL_TGT.ODS_BUSINESS_DATE AS TRF_IFL_TGT_ODS_BUSINESS_DATE,
            	TRF_IFL_TGT.ORG_INR_PTY_FLAG AS TRF_IFL_TGT_ORG_INR_PTY_FLAG,
            	TRF_IFL_TGT.SRC_STM_CD AS TRF_IFL_TGT_SRC_STM_CD,
            	TRF_IFL_TGT.IP_IDENTN_TP AS TRF_IFL_TGT_IP_IDENTN_TP,
            	TRF_IFL_TGT.REPORTING_DATE AS TRF_IFL_TGT_REPORTING_DATE,
            	TRF_IFL_TGT.NAME_1 AS TRF_IFL_TGT_NAME_1,
            	TRF_IFL_TGT.NAME_2 AS TRF_IFL_TGT_NAME_2,
            	TRF_IFL_TGT.MNEMONIC AS TRF_IFL_TGT_MNEMONIC,
            	TRF_IFL_TGT.SECTOR AS TRF_IFL_TGT_SECTOR,
            	TRF_IFL_TGT.SECTOR_NAME AS TRF_IFL_TGT_SECTOR_NAME,
            	TRF_IFL_TGT.NATIONALITY AS TRF_IFL_TGT_NATIONALITY,
            	TRF_IFL_TGT.RESIDENCE AS TRF_IFL_TGT_RESIDENCE,
            	TRF_IFL_TGT.GRID_ID AS TRF_IFL_TGT_GRID_ID,
            	TRF_IFL_TGT.GLOB_COMP AS TRF_IFL_TGT_GLOB_COMP,
            	TRF_IFL_TGT.ULTIMATE_PARENT AS TRF_IFL_TGT_ULTIMATE_PARENT,
            	TRF_IFL_TGT.CONTRACT_DATE AS TRF_IFL_TGT_CONTRACT_DATE,
            	TRF_IFL_TGT.CUSTOMER_STATUS AS TRF_IFL_TGT_CUSTOMER_STATUS,
            	TRF_IFL_TGT.CURR_NO AS TRF_IFL_TGT_CURR_NO,
            	TRF_IFL_TGT.DATE_TIME AS TRF_IFL_TGT_DATE_TIME,
            	TRF_IFL_TGT.FIRST_INPUTTER AS TRF_IFL_TGT_FIRST_INPUTTER,
            	TRF_IFL_TGT.LAST_INPUTTER AS TRF_IFL_TGT_LAST_INPUTTER,
            	TRF_IFL_TGT.AUTHORISER AS TRF_IFL_TGT_AUTHORISER,
            	TRF_IFL_TGT.REPORTING_DT AS TRF_IFL_TGT_REPORTING_DT,
            	TRF_IFL_TGT.REL_START_DATE AS TRF_IFL_TGT_REL_START_DATE,
            	CL_CV_V.CL_CD AS CL_CV_V_CL_CD,
            	CL_CV_V.CL_SUP_KEY AS CL_CV_V_CL_SUP_KEY
        FROM
            {{ ref('trf_ifl_tgt') }} AS TRF_IFL_TGT
            LEFT OUTER JOIN {{ ref('cl_cv_v') }} AS CL_CV_V ON CL_CV_V.CL_SUP_KEY=TRF_IFL_TGT.IP_IDENTN_TP 
)

SELECT * FROM lkp_cl_v

