
{{config(
  materialized='ephemeral'
)}}

WITH lnk_ifl_cust AS (
SELECT
            		TRF_IFL_TGT_NAME_1 AS NAME_1,
            	TRF_IFL_TGT_NAME_2 AS NAME_2,
            	TRF_IFL_TGT_MNEMONIC AS MNEMONIC,
            	TRF_IFL_TGT_SECTOR AS SECTOR,
            	TRF_IFL_TGT_SECTOR_NAME AS SECTOR_NAME,
            	TRF_IFL_TGT_NATIONALITY AS NATIONALITY,
            	TRF_IFL_TGT_RESIDENCE AS RESIDENCE,
            	TRF_IFL_TGT_GRID_ID AS GRID_ID,
            	TRF_IFL_TGT_GLOB_COMP AS GLOB_COMP,
            	TRF_IFL_TGT_ULTIMATE_PARENT AS ULTIMATE_PARENT,
            	TRF_IFL_TGT_CONTRACT_DATE AS CONTRACT_DATE,
            	TRF_IFL_TGT_CUSTOMER_STATUS AS CUSTOMER_STATUS,
            	TRF_IFL_TGT_CURR_NO AS CURR_NO,
            	TRF_IFL_TGT_DATE_TIME AS DATE_TIME,
            	TRF_IFL_TGT_FIRST_INPUTTER AS FIRST_INPUTTER,
            	TRF_IFL_TGT_LAST_INPUTTER AS LAST_INPUTTER,
            	TRF_IFL_TGT_AUTHORISER AS AUTHORISER,
            	TRF_IFL_TGT_REPORTING_DT AS REPORTING_DT,
            	TRF_IFL_TGT_REL_START_DATE AS REL_START_DATE,
            	TRF_IFL_TGT_REL_END_DATE AS REL_END_DATE,
            	TRF_IFL_TGT_ODS_BUSINESS_DATE AS ODS_BUSINESS_DATE,
            	TRF_IFL_TGT_ORG_INR_PTY_FLAG AS ORG_INR_PTY_FLAG,
            	TRF_IFL_TGT_SRC_STM_CD AS SRC_STM_CD,
            	CL_CV_V_CL_CD AS IP_IDENTN_TP,
            	TRF_IFL_TGT_REPORTING_DATE AS REPORTING_DATE
        FROM
            {{ ref('lkp_cl_v') }} AS LKP_CL_V 
)

SELECT * FROM lnk_ifl_cust

