
{{config(
  materialized='ephemeral'
)}}

WITH mov_xfm_fcy_ar_src_m1 AS (
SELECT
            		MOV_JNI_TXN_FCY_RK_AGMNT.SRC_DL AS SRC_DL,
            	MOV_JNI_TXN_FCY_RK_AGMNT.FCY_RK AS FCY_RK,
            	NULL AS SYS_INRT_TMS,
            	MOV_JNI_TXN_FCY_RK_AGMNT.DATA_DT AS DATA_DT,
            	MOV_JNI_TXN_FCY_RK_AGMNT.EV_ID AS EV_ID,
            	MOV_JNI_TXN_FCY_RK_AGMNT.MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	MOV_JNI_TXN_FCY_RK_AGMNT.MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	MOV_JNI_TXN_FCY_RK_AGMNT.VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_JNI_TXN_FCY_RK_AGMNT.VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_JNI_TXN_FCY_RK_AGMNT.PRIM_AR_ID AS PRIM_AR_ID,
            	MOV_JNI_TXN_FCY_RK_AGMNT.TXN_BOOK_DT AS TXN_BOOK_DT,
            	MOV_JNI_TXN_FCY_RK_AGMNT.TXN_CCY_AMT AS TXN_CCY_AMT,
            	MOV_JNI_TXN_FCY_RK_AGMNT.TXN_CCY_CL_CD AS TXN_CCY_CL_CD,
            	MOV_JNI_TXN_FCY_RK_AGMNT.TXN_RSN_TP_CL_CD AS TXN_RSN_TP_CL_CD,
            	MOV_JNI_TXN_FCY_RK_AGMNT.LDGR_CCY_AMT AS LDGR_CCY_AMT,
            	MOV_JNI_TXN_FCY_RK_AGMNT.LDGR_CCY_CL_CD AS LDGR_CCY_CL_CD
        FROM
            {{ ref('mov_jni_txn_fcy_rk_agmnt') }} AS MOV_JNI_TXN_FCY_RK_AGMNT 
)

SELECT * FROM mov_xfm_fcy_ar_src_m1

