templateproject:
  outputs:
    dev:
      dataset: cognizant_ds_dbt_poc
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: cognizant-pocngdap-01
      threads: 1
      type: bigquery
  target: dev