
version: 2

models:
    - name: customer_dbt_model
      description: "A starter dbt model"
      columns:
          - name: cust_id
            description: "The primary key for this table"
            tests:
                - unique

    - name: transaction_dbt_model
      description: "A starter dbt model"
      columns:
          - name: tran_id
            description: "The primary key for this table"
            tests:
                - unique
