version: 2

sources:
  - name: ing_poc_demo
    database: cognizant-pocngdap-01
    schema: ing_poc_demo
    tables:
      - name: customer
      - name: transaction


  - name: DM_MPSCR
    database: cognizant-pocngdap-01
    schema: DM_MPSCR
    tables:
      - name: EWM_AR_AU_BAL_M


