
sources:

- name: "xg_ps_rdb_dm_mpscr_database.xg_rdb_dm_schema_mpscr"
  description: "Source tables"
  database: "<DATABASE NAME>"
  schema: "xg_ps_rdb_dm_mpscr_database.xg_rdb_dm_schema_mpscr"
  tables:
  - name: "ewm_mdm_stage_crdt_risk_rating"
  - name: "mdm_credit_risk_rating"
  - name: "MDM_CREDIT_RISK_RATING_UPD_DEL"
  - name: "ewm_ip_org_v"
  - name: "ewm_ar_x_cl_rtg_r"
  - name: "ewm_cl_jcog_x_cl_rtg_r"
  - name: "ewm_ip_idv_v"
  - name: "ewm_ar_fcy_ar_v"
  - name: "ewm_ar_fcy_ar_drv_v"
  - name: "ewm_ip_x_cl_rtg_r"
  - name: "ewm_cl_jcog_v"
  - name: "EWM_AR_AU_BAL_M"
