
{{config(
  materialized='ephemeral'
)}}

WITH jno_court_controlled_1 AS (
SELECT
            		MOV_SRT_FCY_AR_FNC_ST.AR_DEFAULT_IND AS MOV_SRT_FCY_AR_FNC_ST_AR_DEFAULT_IND,
            	MOV_SRT_FCY_AR_FNC_ST.SRC_DL AS MOV_SRT_FCY_AR_FNC_ST_SRC_DL,
            	MOV_SRT_FCY_AR_FNC_ST.AR_ID AS MOV_SRT_FCY_AR_FNC_ST_AR_ID,
            	MOV_SRT_FCY_AR_FNC_ST.VLD_FROM_TMS AS MOV_SRT_FCY_AR_FNC_ST_VLD_FROM_TMS,
            	MOV_SRT_FCY_AR_FNC_ST.VLD_TO_TMS AS MOV_SRT_FCY_AR_FNC_ST_VLD_TO_TMS,
            	MOV_SRT_FCY_AR_FNC_ST.MSTR_SRC_STM_CD AS MOV_SRT_FCY_AR_FNC_ST_MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_AR_FNC_ST.MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_FNC_ST_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_FNC_ST.FCY_RK AS MOV_SRT_FCY_AR_FNC_ST_FCY_RK,
            	MOV_SRT_FCY_AR_FNC_ST.DATA_DT AS MOV_SRT_FCY_AR_FNC_ST_DATA_DT,
            	MOV_SRT_FCY_AR_FNC_ST.AR_X_AR_RLTNP_TP_CL_CD AS MOV_SRT_FCY_AR_FNC_ST_AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_AR_FNC_ST.LMTG_AR_MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_FNC_ST_LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_FNC_ST.FCY_AR_TP AS MOV_SRT_FCY_AR_FNC_ST_FCY_AR_TP,
            	MOV_SRT_FCY_AR_FNC_ST.AR_CL_CD AS MOV_SRT_FCY_AR_FNC_ST_AR_CL_CD,
            	MOV_SRT_CRT_CNTRLD_AR_ID.SRC_DL AS MOV_SRT_CRT_CNTRLD_AR_ID_SRC_DL,
            	MOV_SRT_CRT_CNTRLD_AR_ID.EV_ID AS MOV_SRT_CRT_CNTRLD_AR_ID_EV_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID.EV_JDCL_EV_V_ID AS MOV_SRT_CRT_CNTRLD_AR_ID_EV_JDCL_EV_V_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID.ACT_STRT_DT AS MOV_SRT_CRT_CNTRLD_AR_ID_ACT_STRT_DT,
            	MOV_SRT_CRT_CNTRLD_AR_ID.ACT_END_DT AS MOV_SRT_CRT_CNTRLD_AR_ID_ACT_END_DT,
            	MOV_SRT_CRT_CNTRLD_AR_ID.AR_ID AS MOV_SRT_CRT_CNTRLD_AR_ID_AR_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID.IP_ID AS MOV_SRT_CRT_CNTRLD_AR_ID_IP_ID
        FROM
            {{ ref('mov_srt_fcy_ar_fnc_st') }} AS MOV_SRT_FCY_AR_FNC_ST
            LEFT OUTER JOIN {{ ref('mov_srt_crt_cntrld_ar_id') }} AS MOV_SRT_CRT_CNTRLD_AR_ID ON MOV_SRT_FCY_AR_FNC_ST.SRC_DL=MOV_SRT_CRT_CNTRLD_AR_ID.SRC_DL
            AND MOV_SRT_FCY_AR_FNC_ST.AR_ID=MOV_SRT_CRT_CNTRLD_AR_ID.AR_ID 
)

SELECT * FROM jno_court_controlled_1

