
{{config(
  materialized='ephemeral'
)}}

WITH jno_cr_obl_deflt_1 AS (
SELECT
            		MOV_XFM_IP_CL_CD.IP_DEFAULT_IND AS MOV_XFM_IP_CL_CD_IP_DEFAULT_IND,
            	MOV_XFM_IP_CL_CD.SRC_DL AS MOV_XFM_IP_CL_CD_SRC_DL,
            	MOV_XFM_IP_CL_CD.IP_ID AS MOV_XFM_IP_CL_CD_IP_ID,
            	MOV_XFM_IP_CL_CD.IP_CL_CD AS MOV_XFM_IP_CL_CD_IP_CL_CD,
            	MOV_SRT_FCY_IP_RLTNP.AR_DEFAULT_IND AS MOV_SRT_FCY_IP_RLTNP_AR_DEFAULT_IND,
            	MOV_SRT_FCY_IP_RLTNP.SRC_DL AS MOV_SRT_FCY_IP_RLTNP_SRC_DL,
            	MOV_SRT_FCY_IP_RLTNP.AR_ID AS MOV_SRT_FCY_IP_RLTNP_AR_ID,
            	MOV_SRT_FCY_IP_RLTNP.VLD_FROM_TMS AS MOV_SRT_FCY_IP_RLTNP_VLD_FROM_TMS,
            	MOV_SRT_FCY_IP_RLTNP.VLD_TO_TMS AS MOV_SRT_FCY_IP_RLTNP_VLD_TO_TMS,
            	MOV_SRT_FCY_IP_RLTNP.MSTR_SRC_STM_CD AS MOV_SRT_FCY_IP_RLTNP_MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_IP_RLTNP.MSTR_SRC_STM_KEY AS MOV_SRT_FCY_IP_RLTNP_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_IP_RLTNP.FCY_RK AS MOV_SRT_FCY_IP_RLTNP_FCY_RK,
            	MOV_SRT_FCY_IP_RLTNP.DATA_DT AS MOV_SRT_FCY_IP_RLTNP_DATA_DT,
            	MOV_SRT_FCY_IP_RLTNP.AR_X_AR_RLTNP_TP_CL_CD AS MOV_SRT_FCY_IP_RLTNP_AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_IP_RLTNP.LMTG_AR_MSTR_SRC_STM_KEY AS MOV_SRT_FCY_IP_RLTNP_LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_IP_RLTNP.FCY_AR_TP AS MOV_SRT_FCY_IP_RLTNP_FCY_AR_TP,
            	MOV_SRT_FCY_IP_RLTNP.AR_CL_CD AS MOV_SRT_FCY_IP_RLTNP_AR_CL_CD,
            	MOV_SRT_FCY_IP_RLTNP.IP_ID AS MOV_SRT_FCY_IP_RLTNP_IP_ID,
            	MOV_SRT_FCY_IP_RLTNP.EV_ID AS MOV_SRT_FCY_IP_RLTNP_EV_ID,
            	MOV_SRT_FCY_IP_RLTNP.EV_JDCL_EV_V_ID AS MOV_SRT_FCY_IP_RLTNP_EV_JDCL_EV_V_ID,
            	MOV_SRT_FCY_IP_RLTNP.ACT_STRT_DT AS MOV_SRT_FCY_IP_RLTNP_ACT_STRT_DT,
            	MOV_SRT_FCY_IP_RLTNP.ACT_END_DT AS MOV_SRT_FCY_IP_RLTNP_ACT_END_DT
        FROM
            {{ ref('mov_xfm_ip_cl_cd') }} AS MOV_XFM_IP_CL_CD
            LEFT OUTER JOIN {{ ref('mov_srt_fcy_ip_rltnp') }} AS MOV_SRT_FCY_IP_RLTNP ON MOV_XFM_IP_CL_CD.SRC_DL=MOV_SRT_FCY_IP_RLTNP.SRC_DL
            AND MOV_XFM_IP_CL_CD.IP_ID=MOV_SRT_FCY_IP_RLTNP.IP_ID 
)

SELECT * FROM jno_cr_obl_deflt_1

