
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_ar_fcy_ar_tp AS (
SELECT
            		MOV_SRT_FCY_AR_OBJ_AR.SRC_DL AS MOV_SRT_FCY_AR_OBJ_AR_SRC_DL,
            	MOV_SRT_FCY_AR_OBJ_AR.AR_ID AS MOV_SRT_FCY_AR_OBJ_AR_AR_ID,
            	MOV_SRT_FCY_AR_OBJ_AR.VLD_FROM_TMS AS MOV_SRT_FCY_AR_OBJ_AR_VLD_FROM_TMS,
            	MOV_SRT_FCY_AR_OBJ_AR.VLD_TO_TMS AS MOV_SRT_FCY_AR_OBJ_AR_VLD_TO_TMS,
            	MOV_SRT_FCY_AR_OBJ_AR.MSTR_SRC_STM_CD AS MOV_SRT_FCY_AR_OBJ_AR_MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_AR_OBJ_AR.MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_OBJ_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_OBJ_AR.FCY_RK AS MOV_SRT_FCY_AR_OBJ_AR_FCY_RK,
            	MOV_SRT_FCY_AR_OBJ_AR.DATA_DT AS MOV_SRT_FCY_AR_OBJ_AR_DATA_DT,
            	MOV_SRT_FCY_AR_OBJ_AR.OBJ_AR_ID AS MOV_SRT_FCY_AR_OBJ_AR_OBJ_AR_ID,
            	MOV_SRT_FCY_AR_OBJ_AR.SUBJ_AR_ID AS MOV_SRT_FCY_AR_OBJ_AR_SUBJ_AR_ID,
            	MOV_SRT_FCY_AR_OBJ_AR.AR_X_AR_RLTNP_TP_CL_CD AS MOV_SRT_FCY_AR_OBJ_AR_AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_AR_TP AS MOV_SRT_FCY_AR_TP_,
            	MOV_SRT_FCY_AR_TP.OBJ_AR_ID AS MOV_SRT_FCY_AR_TP_OBJ_AR_ID,
            	MOV_SRT_FCY_AR_TP AS MOV_SRT_FCY_AR_TP_,
            	MOV_SRT_FCY_AR_TP.SRC_DL AS MOV_SRT_FCY_AR_TP_SRC_DL,
            	MOV_SRT_FCY_AR_TP.LMTG_AR_MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_TP_LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_TP.FCY_AR_TP AS MOV_SRT_FCY_AR_TP_FCY_AR_TP
        FROM
            {{ ref('mov_srt_fcy_ar_obj_ar') }} AS MOV_SRT_FCY_AR_OBJ_AR
            LEFT OUTER JOIN {{ ref('mov_srt_fcy_ar_tp') }} AS MOV_SRT_FCY_AR_TP ON MOV_SRT_FCY_AR_TP.SRC_DL=MOV_SRT_FCY_AR_OBJ_AR.SRC_DL
            AND MOV_SRT_FCY_AR_TP.OBJ_AR_ID=MOV_SRT_FCY_AR_OBJ_AR.OBJ_AR_ID 
)

SELECT * FROM jno_fcy_ar_fcy_ar_tp

