
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_ar_subj_ar AS (
SELECT
            		MOV_SRT_FCY_AR.SRC_DL AS MOV_SRT_FCY_AR_SRC_DL,
            	MOV_SRT_FCY_AR.AR_ID AS MOV_SRT_FCY_AR_AR_ID,
            	MOV_SRT_FCY_AR.VLD_FROM_TMS AS MOV_SRT_FCY_AR_VLD_FROM_TMS,
            	MOV_SRT_FCY_AR.VLD_TO_TMS AS MOV_SRT_FCY_AR_VLD_TO_TMS,
            	MOV_SRT_FCY_AR.MSTR_SRC_STM_CD AS MOV_SRT_FCY_AR_MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_AR.MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR.FCY_RK AS MOV_SRT_FCY_AR_FCY_RK,
            	MOV_SRT_FCY_AR.DATA_DT AS MOV_SRT_FCY_AR_DATA_DT,
            	MOV_SRT_AR_RLTNP AS MOV_SRT_AR_RLTNP_,
            	MOV_SRT_AR_RLTNP.AR_ID AS MOV_SRT_AR_RLTNP_AR_ID,
            	MOV_SRT_AR_RLTNP AS MOV_SRT_AR_RLTNP_,
            	MOV_SRT_AR_RLTNP.SRC_DL AS MOV_SRT_AR_RLTNP_SRC_DL,
            	MOV_SRT_AR_RLTNP.OBJ_AR_ID AS MOV_SRT_AR_RLTNP_OBJ_AR_ID,
            	MOV_SRT_AR_RLTNP.SUBJ_AR_ID AS MOV_SRT_AR_RLTNP_SUBJ_AR_ID,
            	MOV_SRT_AR_RLTNP.AR_X_AR_RLTNP_TP_CL_CD AS MOV_SRT_AR_RLTNP_AR_X_AR_RLTNP_TP_CL_CD
        FROM
            {{ ref('mov_srt_fcy_ar') }} AS MOV_SRT_FCY_AR
            LEFT OUTER JOIN {{ ref('mov_srt_ar_rltnp') }} AS MOV_SRT_AR_RLTNP ON MOV_SRT_AR_RLTNP.SRC_DL=MOV_SRT_FCY_AR.SRC_DL
            AND MOV_SRT_AR_RLTNP.AR_ID=MOV_SRT_FCY_AR.AR_ID 
)

SELECT * FROM jno_fcy_ar_subj_ar

