
{{config(
  materialized='ephemeral'
)}}

WITH jno_cr_obl_deflt_2 AS (
SELECT
            		MOV_SRT_FCY_AR_ID.SRC_DL AS MOV_SRT_FCY_AR_ID_SRC_DL,
            	MOV_SRT_FCY_AR_ID.AR_ID AS MOV_SRT_FCY_AR_ID_AR_ID,
            	MOV_SRT_FCY_AR_ID.VLD_FROM_TMS AS MOV_SRT_FCY_AR_ID_VLD_FROM_TMS,
            	MOV_SRT_FCY_AR_ID.VLD_TO_TMS AS MOV_SRT_FCY_AR_ID_VLD_TO_TMS,
            	MOV_SRT_FCY_AR_ID.MSTR_SRC_STM_CD AS MOV_SRT_FCY_AR_ID_MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_AR_ID.MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_ID_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_ID.FCY_RK AS MOV_SRT_FCY_AR_ID_FCY_RK,
            	MOV_SRT_FCY_AR_ID.DATA_DT AS MOV_SRT_FCY_AR_ID_DATA_DT,
            	MOV_SRT_FCY_AR_ID.AR_X_AR_RLTNP_TP_CL_CD AS MOV_SRT_FCY_AR_ID_AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_AR_ID.LMTG_AR_MSTR_SRC_STM_KEY AS MOV_SRT_FCY_AR_ID_LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_ID.FCY_AR_TP AS MOV_SRT_FCY_AR_ID_FCY_AR_TP,
            	MOV_XFM_AR_CL_CD.AR_DEFAULT_IND AS MOV_XFM_AR_CL_CD_AR_DEFAULT_IND,
            	MOV_XFM_AR_CL_CD.SRC_DL AS MOV_XFM_AR_CL_CD_SRC_DL,
            	MOV_XFM_AR_CL_CD.AR_ID AS MOV_XFM_AR_CL_CD_AR_ID,
            	MOV_XFM_AR_CL_CD.AR_CL_CD AS MOV_XFM_AR_CL_CD_AR_CL_CD
        FROM
            {{ ref('mov_srt_fcy_ar_id') }} AS MOV_SRT_FCY_AR_ID
            LEFT OUTER JOIN {{ ref('mov_xfm_ar_cl_cd') }} AS MOV_XFM_AR_CL_CD ON MOV_SRT_FCY_AR_ID.SRC_DL=MOV_XFM_AR_CL_CD.SRC_DL
            AND MOV_SRT_FCY_AR_ID.AR_ID=MOV_XFM_AR_CL_CD.AR_ID 
)

SELECT * FROM jno_cr_obl_deflt_2

