
{{config(
  materialized='ephemeral'
)}}

WITH mov_fcy_all AS (
SELECT
            		MOV_FCY_CRT_CTRL.MSTR_SRC_STM_KEY AS FCY_ID,
            	MOV_FCY_CRT_CTRL.FCY_RK AS FCY_RK,
            	MOV_FCY_CRT_CTRL.LMTG_AR_MSTR_SRC_STM_KEY AS UNDRL_AR_ID,
            	MOV_FCY_CRT_CTRL.LMTG_AR_MSTR_SRC_STM_KEY AS FCY_AR_TP,
            	MOV_FCY_CRT_CTRL.EV_JDCL_EV_V_ID AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_FCY_CRT_CTRL.AR_DEFAULT_IND AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_FCY_CRT_CTRL.ACT_STRT_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_FCY_CRT_CTRL.ACT_END_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_FCY_CRT_CTRL.AR_DEFAULT_IND AS CR_OBLG_DFLTD,
            	MOV_FCY_CRT_CTRL.AR_ID AS AR_ID,
            	MOV_FCY_CRT_CTRL.SRC_DL AS SRC_DL,
            	MOV_FCY_CRT_CTRL.DATA_DT AS DATA_DT,
            	MOV_FCY_CRT_CTRL.VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_FCY_CRT_CTRL.VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_FCY_CRT_CTRL.MSTR_SRC_STM_CD AS SRC_STM_ID
        FROM
            {{ ref('mov_fcy_crt_ctrl') }} AS MOV_FCY_CRT_CTRL 
)

SELECT * FROM mov_fcy_all

