
{{config(
  materialized='ephemeral'
)}}

WITH mov_fcy_crt_ctrl AS (
SELECT
            		MOV_SRT_FCY_IP_RLTNP_AR_DEFAULT_IND AS AR_DEFAULT_IND,
            	MOV_XFM_IP_CL_CD_IP_DEFAULT_IND AS IP_DEFAULT_IND,
            	MOV_SRT_FCY_IP_RLTNP_SRC_DL AS SRC_DL,
            	MOV_SRT_FCY_IP_RLTNP_AR_ID AS AR_ID,
            	MOV_SRT_FCY_IP_RLTNP_VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_SRT_FCY_IP_RLTNP_VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_SRT_FCY_IP_RLTNP_MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_IP_RLTNP_MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_IP_RLTNP_FCY_RK AS FCY_RK,
            	MOV_SRT_FCY_IP_RLTNP_DATA_DT AS DATA_DT,
            	MOV_SRT_FCY_IP_RLTNP_AR_X_AR_RLTNP_TP_CL_CD AS AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_IP_RLTNP_LMTG_AR_MSTR_SRC_STM_KEY AS LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_IP_RLTNP_FCY_AR_TP AS FCY_AR_TP,
            	MOV_SRT_FCY_IP_RLTNP_AR_CL_CD AS AR_CL_CD,
            	MOV_SRT_FCY_IP_RLTNP_IP_ID AS IP_ID,
            	MOV_SRT_FCY_IP_RLTNP_EV_ID AS EV_ID,
            	MOV_SRT_FCY_IP_RLTNP_EV_JDCL_EV_V_ID AS EV_JDCL_EV_V_ID,
            	MOV_SRT_FCY_IP_RLTNP_ACT_STRT_DT AS ACT_STRT_DT,
            	MOV_SRT_FCY_IP_RLTNP_ACT_END_DT AS ACT_END_DT,
            	MOV_XFM_IP_CL_CD_IP_CL_CD AS IP_CL_CD
        FROM
            {{ ref('jno_cr_obl_deflt_1') }} AS JNO_CR_OBL_DEFLT_1 
)

SELECT * FROM mov_fcy_crt_ctrl

