
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_fcy_ip_rltnp AS (
SELECT
            		MOV_JNO_COURT_CONTROLLED_1.AR_DEFAULT_IND AS AR_DEFAULT_IND,
            	MOV_JNO_COURT_CONTROLLED_1.SRC_DL AS SRC_DL,
            	MOV_JNO_COURT_CONTROLLED_1.AR_ID AS AR_ID,
            	MOV_JNO_COURT_CONTROLLED_1.VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_JNO_COURT_CONTROLLED_1.VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_JNO_COURT_CONTROLLED_1.MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	MOV_JNO_COURT_CONTROLLED_1.MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	MOV_JNO_COURT_CONTROLLED_1.FCY_RK AS FCY_RK,
            	MOV_JNO_COURT_CONTROLLED_1.DATA_DT AS DATA_DT,
            	MOV_JNO_COURT_CONTROLLED_1.AR_X_AR_RLTNP_TP_CL_CD AS AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_JNO_COURT_CONTROLLED_1.LMTG_AR_MSTR_SRC_STM_KEY AS LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_JNO_COURT_CONTROLLED_1.FCY_AR_TP AS FCY_AR_TP,
            	MOV_JNO_COURT_CONTROLLED_1.AR_CL_CD AS AR_CL_CD,
            	MOV_JNO_COURT_CONTROLLED_1.IP_ID AS IP_ID,
            	MOV_JNO_COURT_CONTROLLED_1.EV_ID AS EV_ID,
            	MOV_JNO_COURT_CONTROLLED_1.EV_JDCL_EV_V_ID AS EV_JDCL_EV_V_ID,
            	MOV_JNO_COURT_CONTROLLED_1.ACT_STRT_DT AS ACT_STRT_DT,
            	MOV_JNO_COURT_CONTROLLED_1.ACT_END_DT AS ACT_END_DT
        FROM
            {{ ref('mov_jno_court_controlled_1') }} AS MOV_JNO_COURT_CONTROLLED_1
        ORDER BY
            SRC_DL ASC,
            IP_ID ASC 
)

SELECT * FROM mov_srt_fcy_ip_rltnp

