
{{config(
  materialized='ephemeral'
)}}

WITH mov_jno_court_controlled_1 AS (
SELECT
            		MOV_SRT_FCY_AR_FNC_ST_AR_DEFAULT_IND AS AR_DEFAULT_IND,
            	MOV_SRT_FCY_AR_FNC_ST_SRC_DL AS SRC_DL,
            	MOV_SRT_FCY_AR_FNC_ST_AR_ID AS AR_ID,
            	MOV_SRT_FCY_AR_FNC_ST_VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_SRT_FCY_AR_FNC_ST_VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_SRT_FCY_AR_FNC_ST_MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	MOV_SRT_FCY_AR_FNC_ST_MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_FNC_ST_FCY_RK AS FCY_RK,
            	MOV_SRT_FCY_AR_FNC_ST_DATA_DT AS DATA_DT,
            	MOV_SRT_FCY_AR_FNC_ST_AR_X_AR_RLTNP_TP_CL_CD AS AR_X_AR_RLTNP_TP_CL_CD,
            	MOV_SRT_FCY_AR_FNC_ST_LMTG_AR_MSTR_SRC_STM_KEY AS LMTG_AR_MSTR_SRC_STM_KEY,
            	MOV_SRT_FCY_AR_FNC_ST_FCY_AR_TP AS FCY_AR_TP,
            	MOV_SRT_FCY_AR_FNC_ST_AR_CL_CD AS AR_CL_CD,
            	MOV_SRT_CRT_CNTRLD_AR_ID_IP_ID AS IP_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID_EV_ID AS EV_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID_EV_JDCL_EV_V_ID AS EV_JDCL_EV_V_ID,
            	MOV_SRT_CRT_CNTRLD_AR_ID_ACT_STRT_DT AS ACT_STRT_DT,
            	MOV_SRT_CRT_CNTRLD_AR_ID_ACT_END_DT AS ACT_END_DT
        FROM
            {{ ref('jno_court_controlled_1') }} AS JNO_COURT_CONTROLLED_1 
)

SELECT * FROM mov_jno_court_controlled_1

