
{{ config(
 materialized='table',
 post_hook="
 INSERT INTO
    {{ source('DM_MPSCR', 'EWM_MDM_STAGE_FCY_AR_IP_JDCL') }}
 (SRC_DL,
DATA_DT,
VLD_FROM_TMS,
VLD_TO_TMS,
SRC_STM_ID,
FCY_ID,
FCY_RK,
AR_ID,
FCY_AR_TP,
COURT_CTRLD_WRKOUT_FCY,
OUT_OF_COURT_WRKOUT_FCY,
COURT_CTRLD_WRKOUT_FILL_DT,
COURT_CTRLD_WRKOUT_CLS_DT,
CR_OBLG_DFLTD,
UNDRL_AR_ID,
SYS_INRT_TMS)
                                                        SELECT SRC_DL,
DATA_DT,
VLD_FROM_TMS,
VLD_TO_TMS,
SRC_STM_ID,
FCY_ID,
FCY_RK,
AR_ID,
FCY_AR_TP,
cast(COURT_CTRLD_WRKOUT_FCY as String) as COURT_CTRLD_WRKOUT_FCY,
OUT_OF_COURT_WRKOUT_FCY,
COURT_CTRLD_WRKOUT_FILL_DT,
COURT_CTRLD_WRKOUT_CLS_DT,
CR_OBLG_DFLTD,
UNDRL_AR_ID,
CAST(SYS_INRT_TMS AS DATETIME) AS SYS_INRT_TMS
FROM
    {{ ref('wri_flt_mdm_fcy') }}
 "
)}}

SELECT 1 AS dummy_column

