
{{config(
  materialized='ephemeral'
)}}

WITH jnf_mdm_fcy AS (
SELECT
            		MOV_FCY_SRC.FCY_ID AS MOV_FCY_SRC_FCY_ID,
            	MOV_FCY_SRC.SRC_ID AS MOV_FCY_SRC_SRC_ID,
            	MOV_FCY_SRC.DATE_FROM AS MOV_FCY_SRC_DATE_FROM,
            	MOV_FCY_SRC.AR_ID AS MOV_FCY_SRC_AR_ID,
            	MOV_FCY_SRC.DATE_TO AS MOV_FCY_SRC_DATE_TO,
            	MOV_FCY_SRC.SRC_DL AS MOV_FCY_SRC_SRC_DL,
            	MOV_FCY_SRC.FCY_RK AS MOV_FCY_SRC_FCY_RK,
            	MOV_FCY_SRC.FCY_AR_TP AS MOV_FCY_SRC_FCY_AR_TP,
            	MOV_FCY_SRC.HIGHER_FCY_RK AS MOV_FCY_SRC_HIGHER_FCY_RK,
            	MOV_FCY_SRC.HIGHEST_FCY_RK AS MOV_FCY_SRC_HIGHEST_FCY_RK,
            	MOV_FCY_SRC.LOWEST_LVL_IND AS MOV_FCY_SRC_LOWEST_LVL_IND,
            	MOV_FCY_SRC.SPSDG_FCY_RK AS MOV_FCY_SRC_SPSDG_FCY_RK,
            	MOV_FCY_SRC.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_FCY_SRC_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_FCY_SRC.COURT_CTRLD_WRKOUT_FCY AS MOV_FCY_SRC_COURT_CTRLD_WRKOUT_FCY,
            	MOV_FCY_SRC.OUT_OF_COURT_WRKOUT_FCY AS MOV_FCY_SRC_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_FCY_SRC.SPSDG_FCY_DT AS MOV_FCY_SRC_SPSDG_FCY_DT,
            	MOV_FCY_SRC.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_FCY_SRC_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_FCY_SRC.CR_OBLG_DFLTD AS MOV_FCY_SRC_CR_OBLG_DFLTD,
            	MOV_FCY_SRC.FCY_VORTEX_ID AS MOV_FCY_SRC_FCY_VORTEX_ID,
            	MOV_MDM_FCY_TGT.FCY_ID AS MOV_MDM_FCY_TGT_FCY_ID,
            	MOV_MDM_FCY_TGT.SRC_ID AS MOV_MDM_FCY_TGT_SRC_ID,
            	MOV_MDM_FCY_TGT.DATE_FROM AS MOV_MDM_FCY_TGT_DATE_FROM,
            	MOV_MDM_FCY_TGT.TGT_DATE_TO AS MOV_MDM_FCY_TGT_TGT_DATE_TO,
            	MOV_MDM_FCY_TGT.AR_ID AS MOV_MDM_FCY_TGT_AR_ID,
            	MOV_MDM_FCY_TGT.SRC_DL AS MOV_MDM_FCY_TGT_SRC_DL,
            	MOV_MDM_FCY_TGT.TGT_FCY_RK AS MOV_MDM_FCY_TGT_TGT_FCY_RK,
            	MOV_MDM_FCY_TGT.TGT_FCY_AR_TP AS MOV_MDM_FCY_TGT_TGT_FCY_AR_TP,
            	MOV_MDM_FCY_TGT.TGT_HIGHER_FCY_RK AS MOV_MDM_FCY_TGT_TGT_HIGHER_FCY_RK,
            	MOV_MDM_FCY_TGT.TGT_HIGHEST_FCY_RK AS MOV_MDM_FCY_TGT_TGT_HIGHEST_FCY_RK,
            	MOV_MDM_FCY_TGT.TGT_LOWEST_LVL_IND AS MOV_MDM_FCY_TGT_TGT_LOWEST_LVL_IND,
            	MOV_MDM_FCY_TGT.TGT_SPSDG_FCY_RK AS MOV_MDM_FCY_TGT_TGT_SPSDG_FCY_RK,
            	MOV_MDM_FCY_TGT.TGT_COURT_CTRLD_WRKOUT_FILL_DT AS MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_MDM_FCY_TGT.TGT_COURT_CTRLD_WRKOUT_FCY AS MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_FCY,
            	MOV_MDM_FCY_TGT.TGT_OUT_OF_COURT_WRKOUT_FCY AS MOV_MDM_FCY_TGT_TGT_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_MDM_FCY_TGT.TGT_SPSDG_FCY_DT AS MOV_MDM_FCY_TGT_TGT_SPSDG_FCY_DT,
            	MOV_MDM_FCY_TGT.TGT_COURT_CTRLD_WRKOUT_CLS_DT AS MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_MDM_FCY_TGT.TGT_CR_OBLG_DFLTD AS MOV_MDM_FCY_TGT_TGT_CR_OBLG_DFLTD,
            	MOV_MDM_FCY_TGT.TGT_FCY_VORTEX_ID AS MOV_MDM_FCY_TGT_TGT_FCY_VORTEX_ID,
            	MOV_MDM_FCY_TGT.TGT_DATE_FROM AS MOV_MDM_FCY_TGT_TGT_DATE_FROM
        FROM
            {{ ref('mov_fcy_src') }} AS MOV_FCY_SRC
            FULL OUTER JOIN {{ ref('mov_mdm_fcy_tgt') }} AS MOV_MDM_FCY_TGT ON MOV_MDM_FCY_TGT.SRC_ID=MOV_FCY_SRC.SRC_ID
            AND MOV_MDM_FCY_TGT.FCY_ID=MOV_FCY_SRC.FCY_ID
            AND MOV_MDM_FCY_TGT.AR_ID=MOV_FCY_SRC.AR_ID
            AND MOV_MDM_FCY_TGT.SRC_DL=MOV_FCY_SRC.SRC_DL
            AND MOV_MDM_FCY_TGT.DATE_FROM=MOV_FCY_SRC.DATE_FROM 
)

SELECT * FROM jnf_mdm_fcy

