
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_src_keys AS (
SELECT
            		REA_MDM_FCY_SCD.FCY_ID AS FCY_ID,
            	REA_MDM_FCY_SCD.SRC_STM_ID AS SRC_ID,
            	REA_MDM_FCY_SCD.DATE_FROM AS DATE_FROM,
            	REA_MDM_FCY_SCD.AR_ID AS AR_ID,
            	REA_MDM_FCY_SCD.DATE_TO AS DATE_TO,
            	REA_MDM_FCY_SCD.SRC_DL AS SRC_DL,
            	REA_MDM_FCY_SCD.FCY_RK AS FCY_RK,
            	REA_MDM_FCY_SCD.FCY_AR_TP AS FCY_AR_TP,
            	REA_MDM_FCY_SCD.HIGHER_FCY_RK AS HIGHER_FCY_RK,
            	REA_MDM_FCY_SCD.HIGHEST_FCY_RK AS HIGHEST_FCY_RK,
            	REA_MDM_FCY_SCD.LOWEST_LVL_IND AS LOWEST_LVL_IND,
            	REA_MDM_FCY_SCD.SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	REA_MDM_FCY_SCD.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	REA_MDM_FCY_SCD.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	REA_MDM_FCY_SCD.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	REA_MDM_FCY_SCD.SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	REA_MDM_FCY_SCD.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	REA_MDM_FCY_SCD.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	REA_MDM_FCY_SCD.FCY_VORTEX_ID AS FCY_VORTEX_ID
        FROM
            {{ ref('rea_mdm_fcy_scd') }} AS REA_MDM_FCY_SCD
        ORDER BY
            SRC_STM_ID ASC,
            FCY_ID ASC,
            AR_ID ASC,
            SRC_DL ASC,
            DATE_FROM ASC 
)

SELECT * FROM mov_srt_src_keys

