
{{config(
  materialized='ephemeral'
)}}

WITH mov_jno_facility AS (
SELECT
            		MOV_FCY_SRC_FCY_ID AS FCY_ID,
            	MOV_FCY_SRC_SRC_ID AS SRC_ID,
            	MOV_FCY_SRC_DATE_FROM AS DATE_FROM,
            	MOV_FCY_SRC_AR_ID AS AR_ID,
            	MOV_FCY_SRC_DATE_TO AS DATE_TO,
            	MOV_FCY_SRC_SRC_DL AS SRC_DL,
            	MOV_FCY_SRC_FCY_RK AS FCY_RK,
            	MOV_FCY_SRC_FCY_AR_TP AS FCY_AR_TP,
            	MOV_FCY_SRC_HIGHER_FCY_RK AS HIGHER_FCY_RK,
            	MOV_FCY_SRC_HIGHEST_FCY_RK AS HIGHEST_FCY_RK,
            	MOV_FCY_SRC_LOWEST_LVL_IND AS LOWEST_LVL_IND,
            	MOV_FCY_SRC_SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_FCY_SRC_COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_FCY_SRC_COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_FCY_SRC_OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_FCY_SRC_SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_FCY_SRC_COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_FCY_SRC_CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_FCY_SRC_FCY_VORTEX_ID AS FCY_VORTEX_ID,
            	MOV_MDM_FCY_TGT_FCY_ID AS TGT_FCY_ID,
            	MOV_MDM_FCY_TGT_SRC_ID AS TGT_SRC_ID,
            	MOV_MDM_FCY_TGT_TGT_DATE_FROM AS TGT_DATE_FROM,
            	MOV_MDM_FCY_TGT_TGT_DATE_TO AS TGT_DATE_TO,
            	MOV_MDM_FCY_TGT_AR_ID AS TGT_AR_ID,
            	MOV_MDM_FCY_TGT_SRC_DL AS TGT_SRC_DL,
            	MOV_MDM_FCY_TGT_TGT_FCY_RK AS TGT_FCY_RK,
            	MOV_MDM_FCY_TGT_TGT_FCY_AR_TP AS TGT_FCY_AR_TP,
            	MOV_MDM_FCY_TGT_TGT_HIGHER_FCY_RK AS TGT_HIGHER_FCY_RK,
            	MOV_MDM_FCY_TGT_TGT_HIGHEST_FCY_RK AS TGT_HIGHEST_FCY_RK,
            	MOV_MDM_FCY_TGT_TGT_LOWEST_LVL_IND AS TGT_LOWEST_LVL_IND,
            	MOV_MDM_FCY_TGT_TGT_SPSDG_FCY_RK AS TGT_SPSDG_FCY_RK,
            	MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_FILL_DT AS TGT_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_FCY AS TGT_COURT_CTRLD_WRKOUT_FCY,
            	MOV_MDM_FCY_TGT_TGT_OUT_OF_COURT_WRKOUT_FCY AS TGT_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_MDM_FCY_TGT_TGT_SPSDG_FCY_DT AS TGT_SPSDG_FCY_DT,
            	MOV_MDM_FCY_TGT_TGT_COURT_CTRLD_WRKOUT_CLS_DT AS TGT_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_MDM_FCY_TGT_TGT_CR_OBLG_DFLTD AS TGT_CR_OBLG_DFLTD,
            	MOV_MDM_FCY_TGT_TGT_FCY_VORTEX_ID AS TGT_FCY_VORTEX_ID
        FROM
            {{ ref('jnf_mdm_fcy') }} AS JNF_MDM_FCY 
)

SELECT * FROM mov_jno_facility

