
{{config(
  materialized='ephemeral'
)}}

WITH mov_mdm_fcy_tgt AS (
SELECT
            		REA_MDM_FACILITY.FCY_ID AS FCY_ID,
            	REA_MDM_FACILITY.SRC_ID AS SRC_ID,
            	REA_MDM_FACILITY.DATE_FROM AS DATE_FROM,
            	REA_MDM_FACILITY.DATE_TO AS TGT_DATE_TO,
            	REA_MDM_FACILITY.AR_ID AS AR_ID,
            	REA_MDM_FACILITY.SRC_DL AS SRC_DL,
            	REA_MDM_FACILITY.FCY_RK AS TGT_FCY_RK,
            	REA_MDM_FACILITY.FCY_AR_TP AS TGT_FCY_AR_TP,
            	REA_MDM_FACILITY.HIGHER_FCY_RK AS TGT_HIGHER_FCY_RK,
            	REA_MDM_FACILITY.HIGHEST_FCY_RK AS TGT_HIGHEST_FCY_RK,
            	REA_MDM_FACILITY.LOWEST_LVL_IND AS TGT_LOWEST_LVL_IND,
            	REA_MDM_FACILITY.SPSDG_FCY_RK AS TGT_SPSDG_FCY_RK,
            	REA_MDM_FACILITY.COURT_CTRLD_WRKOUT_FILL_DT AS TGT_COURT_CTRLD_WRKOUT_FILL_DT,
            	REA_MDM_FACILITY.COURT_CTRLD_WRKOUT_FCY AS TGT_COURT_CTRLD_WRKOUT_FCY,
            	REA_MDM_FACILITY.OUT_OF_COURT_WRKOUT_FCY AS TGT_OUT_OF_COURT_WRKOUT_FCY,
            	REA_MDM_FACILITY.SPSDG_FCY_DT AS TGT_SPSDG_FCY_DT,
            	REA_MDM_FACILITY.COURT_CTRLD_WRKOUT_CLS_DT AS TGT_COURT_CTRLD_WRKOUT_CLS_DT,
            	REA_MDM_FACILITY.CR_OBLG_DFLTD AS TGT_CR_OBLG_DFLTD,
            	REA_MDM_FACILITY.FCY_VORTEX_ID AS TGT_FCY_VORTEX_ID,
            	REA_MDM_FACILITY.TGT_DATE_FROM AS TGT_DATE_FROM
        FROM
            {{ ref('rea_mdm_facility') }} AS REA_MDM_FACILITY
        ORDER BY
            SRC_ID ASC,
            FCY_ID ASC,
            AR_ID ASC,
            SRC_DL ASC,
            DATE_FROM ASC 
)

SELECT * FROM mov_mdm_fcy_tgt

