
{{config(
  materialized='ephemeral'
)}}

WITH mov_fcy_src AS (
SELECT
            		MOV_SRT_SRC_KEYS.FCY_ID AS FCY_ID,
            	MOV_SRT_SRC_KEYS.SRC_ID AS SRC_ID,
            	MOV_SRT_SRC_KEYS.DATE_FROM AS DATE_FROM,
            	MOV_SRT_SRC_KEYS.AR_ID AS AR_ID,
            	MOV_SRT_SRC_KEYS.DATE_TO AS DATE_TO,
            	MOV_SRT_SRC_KEYS.SRC_DL AS SRC_DL,
            	MOV_SRT_SRC_KEYS.FCY_RK AS FCY_RK,
            	MOV_SRT_SRC_KEYS.FCY_AR_TP AS FCY_AR_TP,
            	MOV_SRT_SRC_KEYS.HIGHER_FCY_RK AS HIGHER_FCY_RK,
            	MOV_SRT_SRC_KEYS.HIGHEST_FCY_RK AS HIGHEST_FCY_RK,
            	MOV_SRT_SRC_KEYS.LOWEST_LVL_IND AS LOWEST_LVL_IND,
            	MOV_SRT_SRC_KEYS.SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_SRT_SRC_KEYS.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_SRC_KEYS.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_SRC_KEYS.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_SRC_KEYS.SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_SRT_SRC_KEYS.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_SRC_KEYS.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_SRT_SRC_KEYS.FCY_VORTEX_ID AS FCY_VORTEX_ID
        FROM
            {{ ref('mov_srt_src_keys') }} AS MOV_SRT_SRC_KEYS 
)

SELECT * FROM mov_fcy_src

