
{{config(
  materialized='ephemeral'
)}}

WITH wri_xfm_mdm_fcy_inrt AS (
SELECT
            		MOV_JNO_FACILITY.FCY_ID AS FCY_ID,
            	MOV_JNO_FACILITY.SRC_ID AS SRC_ID,
            	MOV_JNO_FACILITY.DATE_FROM AS DATE_FROM,
            	MOV_JNO_FACILITY.DATE_TO AS DATE_TO,
            	MOV_JNO_FACILITY.AR_ID AS AR_ID,
            	MOV_JNO_FACILITY.SRC_DL AS SRC_DL,
            	MOV_JNO_FACILITY.FCY_RK AS FCY_RK,
            	MOV_JNO_FACILITY.FCY_AR_TP AS FCY_AR_TP,
            	MOV_JNO_FACILITY.HIGHER_FCY_RK AS HIGHER_FCY_RK,
            	MOV_JNO_FACILITY.HIGHEST_FCY_RK AS HIGHEST_FCY_RK,
            	MOV_JNO_FACILITY.LOWEST_LVL_IND AS LOWEST_LVL_IND,
            	MOV_JNO_FACILITY.SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_JNO_FACILITY.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_JNO_FACILITY.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_JNO_FACILITY.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_JNO_FACILITY.SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_JNO_FACILITY.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_JNO_FACILITY.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_JNO_FACILITY.FCY_VORTEX_ID AS FCY_VORTEX_ID,
            	TIMESTAMP('{{ run_started_at }}') AS SYS_INRT_TMS,
            	 '0' AS DEL_IN_SRC_STM_F
        FROM
            {{ ref('mov_jno_facility') }} AS MOV_JNO_FACILITY
        WHERE
            SVACTION="I"
            OR SVACTION="U" 
)

SELECT * FROM wri_xfm_mdm_fcy_inrt

