
{{config(
  materialized='ephemeral'
)}}

WITH fnl_txn_fcy_rk AS (
SELECT
                    		REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.EV_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_EV_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.MSTR_SRC_STM_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.MSTR_SRC_STM_KEY AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_KEY,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.VLD_FROM_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_FROM_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.VLD_TO_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_TO_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.PRIM_AR_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_PRIM_AR_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.FCY_RK AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_FCY_RK,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.TXN_BOOK_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_BOOK_DT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.TXN_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.TXN_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.TXN_RSN_TP_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_RSN_TP_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.LDGR_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.LDGR_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.SRC_DL AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_SRC_DL,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER.DATA_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_DATA_DT
                FROM
                    {{ ref('rea_ewm_mdm_stage_txn_fcy_rk_master') }} AS REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER
                UNION DISTINCT
                SELECT
                    		REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.EV_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_EV_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.MSTR_SRC_STM_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_MSTR_SRC_STM_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.MSTR_SRC_STM_KEY AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_MSTR_SRC_STM_KEY,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.VLD_FROM_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_VLD_FROM_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.VLD_TO_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_VLD_TO_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.PRIM_AR_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_PRIM_AR_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.FCY_RK AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_FCY_RK,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.TXN_BOOK_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_TXN_BOOK_DT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.TXN_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_TXN_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.TXN_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_TXN_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.TXN_RSN_TP_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_TXN_RSN_TP_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.LDGR_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_LDGR_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.LDGR_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_LDGR_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.SRC_DL AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_SRC_DL,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT.DATA_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT_DATA_DT
                FROM
                    {{ ref('rea_ewm_mdm_stage_txn_fcy_rk_agrmt') }} AS REA_EWM_MDM_STAGE_TXN_FCY_RK_AGRMT
                UNION DISTINCT
                SELECT
                    		REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.EV_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_EV_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.MSTR_SRC_STM_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_MSTR_SRC_STM_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.MSTR_SRC_STM_KEY AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_MSTR_SRC_STM_KEY,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.VLD_FROM_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_VLD_FROM_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.VLD_TO_TMS AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_VLD_TO_TMS,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.PRIM_AR_ID AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_PRIM_AR_ID,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.FCY_RK AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_FCY_RK,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.TXN_BOOK_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_TXN_BOOK_DT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.TXN_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_TXN_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.TXN_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_TXN_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.TXN_RSN_TP_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_TXN_RSN_TP_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.LDGR_CCY_AMT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_LDGR_CCY_AMT,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.LDGR_CCY_CL_CD AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_LDGR_CCY_CL_CD,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.SRC_DL AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_SRC_DL,
                    	REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT.DATA_DT AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT_DATA_DT
                FROM
                    {{ ref('rea_ewm_mdm_stage_txn_fcy_rk_direct') }} AS REA_EWM_MDM_STAGE_TXN_FCY_RK_DIRECT
            ) 
)

SELECT * FROM fnl_txn_fcy_rk

