
{{config(
  materialized='ephemeral'
)}}

WITH mov_fnl_txn_fcy_rk AS (
SELECT
    rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_EV_ID AS EV_ID,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_FROM_TMS AS VLD_FROM_TMS,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_TO_TMS AS VLD_TO_TMS,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_PRIM_AR_ID AS PRIM_AR_ID,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_FCY_RK AS FCY_RK,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_BOOK_DT AS TXN_BOOK_DT,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_AMT AS TXN_CCY_AMT,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_CL_CD AS TXN_CCY_CL_CD,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_RSN_TP_CL_CD AS TXN_RSN_TP_CL_CD,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_AMT AS LDGR_CCY_AMT,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_CL_CD AS LDGR_CCY_CL_CD,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_SRC_DL AS SRC_DL,
rea_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_DATA_DT AS DATA_DT
FROM
    {{ ref('fnl_txn_fcy_rk') }} AS FNL_TXN_FCY_RK
)

SELECT * FROM mov_fnl_txn_fcy_rk

