
{{config(
  materialized='ephemeral'
)}}

WITH mov_fnl_txn_fcy_rk AS (
SELECT
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_EV_ID,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_CD,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_MSTR_SRC_STM_KEY,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_FROM_TMS,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_VLD_TO_TMS,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_PRIM_AR_ID,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_FCY_RK,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_BOOK_DT,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_AMT,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_CCY_CL_CD,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_TXN_RSN_TP_CL_CD,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_AMT,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_LDGR_CCY_CL_CD,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_SRC_DL,
    REA_EWM_MDM_STAGE_TXN_FCY_RK_MASTER_DATA_DT
FROM
    {{ ref('fnl_txn_fcy_rk') }} AS FNL_TXN_FCY_RK
)

SELECT * FROM mov_fnl_txn_fcy_rk

