
{{config(
  materialized='ephemeral'
)}}

WITH mov_fnl_ar_src AS (
SELECT
    REA_EWM_AR_FCY_AR_DRV_V_FCY_RK AS FCY_RK,
REA_EWM_AR_FCY_AR_DRV_V_SRC_DL AS SRC_DL,
REA_EWM_AR_FCY_AR_DRV_V_AR_ID AS AR_ID,
REA_EWM_AR_FCY_AR_DRV_V_MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
REA_EWM_AR_FCY_AR_DRV_V_MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
REA_EWM_AR_FCY_AR_DRV_V_VLD_FROM_TMS AS VLD_FROM_TMS,
REA_EWM_AR_FCY_AR_DRV_V_VLD_TO_TMS AS VLD_TO_TMS,
REA_EWM_AR_FCY_AR_DRV_V_DATA_DT AS DATA_DT
FROM
    {{ ref('fnl_ar_src') }} AS FNL_AR_SRC
)

SELECT * FROM mov_fnl_ar_src

