
{{config(
  materialized='ephemeral'
)}}

WITH jno_txn_fee AS (
SELECT
            		MOV_SRT_EV_TXN.TXN_RK AS MOV_SRT_EV_TXN_TXN_RK,
            	MOV_SRT_EV_TXN.SRC_DL AS MOV_SRT_EV_TXN_SRC_DL,
            	MOV_SRT_EV_TXN.EV_ID AS MOV_SRT_EV_TXN_EV_ID,
            	MOV_SRT_EV_TXN.MSTR_SRC_STM_CD AS MOV_SRT_EV_TXN_MSTR_SRC_STM_CD,
            	MOV_SRT_EV_TXN.MSTR_SRC_STM_KEY AS MOV_SRT_EV_TXN_MSTR_SRC_STM_KEY,
            	MOV_SRT_EV_TXN.VLD_FROM_TMS AS MOV_SRT_EV_TXN_VLD_FROM_TMS,
            	MOV_SRT_EV_TXN.VLD_TO_TMS AS MOV_SRT_EV_TXN_VLD_TO_TMS,
            	MOV_SRT_EV_TXN.PRIM_AR_ID AS MOV_SRT_EV_TXN_PRIM_AR_ID,
            	MOV_SRT_EV_TXN.TXN_BOOK_DT AS MOV_SRT_EV_TXN_TXN_BOOK_DT,
            	MOV_SRT_EV_TXN.TXN_CCY_AMT AS MOV_SRT_EV_TXN_TXN_CCY_AMT,
            	MOV_SRT_EV_TXN.TXN_CCY_CL_CD AS MOV_SRT_EV_TXN_TXN_CCY_CL_CD,
            	MOV_SRT_EV_TXN.TXN_RSN_TP_CL_CD AS MOV_SRT_EV_TXN_TXN_RSN_TP_CL_CD,
            	MOV_SRT_EV_TXN.LDGR_CCY_AMT AS MOV_SRT_EV_TXN_LDGR_CCY_AMT,
            	MOV_SRT_EV_TXN.LDGR_CCY_CL_CD AS MOV_SRT_EV_TXN_LDGR_CCY_CL_CD,
            	MOV_SRT_EV_TXN.DATA_DT AS MOV_SRT_EV_TXN_DATA_DT,
            	MOV_SRT_EV_TXN.FCY_RK AS MOV_SRT_EV_TXN_FCY_RK,
            	MOV_SRT_EV_TXN_FEE.TXN_FEE_CMPT_EV_ID AS MOV_SRT_EV_TXN_FEE_TXN_FEE_CMPT_EV_ID,
            	MOV_SRT_EV_TXN_FEE.SRC_DL AS MOV_SRT_EV_TXN_FEE_SRC_DL,
            	MOV_SRT_EV_TXN_FEE.EV_ID AS MOV_SRT_EV_TXN_FEE_EV_ID,
            	MOV_SRT_EV_TXN_FEE.TXN_FEE_TXN_CCY_AMT AS MOV_SRT_EV_TXN_FEE_TXN_FEE_TXN_CCY_AMT,
            	MOV_SRT_EV_TXN_FEE.TXN_FEE_CCY_CL_CD AS MOV_SRT_EV_TXN_FEE_TXN_FEE_CCY_CL_CD
        FROM
            {{ ref('mov_srt_ev_txn') }} AS MOV_SRT_EV_TXN
            LEFT OUTER JOIN {{ ref('mov_srt_ev_txn_fee') }} AS MOV_SRT_EV_TXN_FEE ON MOV_SRT_EV_TXN.EV_ID=MOV_SRT_EV_TXN_FEE.EV_ID
            AND MOV_SRT_EV_TXN.SRC_DL=MOV_SRT_EV_TXN_FEE.SRC_DL 
)

SELECT * FROM jno_txn_fee

