
{{config(
  materialized='ephemeral'
)}}

WITH jno_ewm_ev_x_cl_r AS (
SELECT
            		MOV_JNO_TXN_FEE.TXN_RK AS MOV_JNO_TXN_FEE_TXN_RK,
            	MOV_JNO_TXN_FEE.TXN_FEE_CMPT_EV_ID AS MOV_JNO_TXN_FEE_TXN_FEE_CMPT_EV_ID,
            	MOV_JNO_TXN_FEE.SRC_DL AS MOV_JNO_TXN_FEE_SRC_DL,
            	MOV_JNO_TXN_FEE.EV_ID AS MOV_JNO_TXN_FEE_EV_ID,
            	MOV_JNO_TXN_FEE.MSTR_SRC_STM_CD AS MOV_JNO_TXN_FEE_MSTR_SRC_STM_CD,
            	MOV_JNO_TXN_FEE.MSTR_SRC_STM_KEY AS MOV_JNO_TXN_FEE_MSTR_SRC_STM_KEY,
            	MOV_JNO_TXN_FEE.VLD_FROM_TMS AS MOV_JNO_TXN_FEE_VLD_FROM_TMS,
            	MOV_JNO_TXN_FEE.VLD_TO_TMS AS MOV_JNO_TXN_FEE_VLD_TO_TMS,
            	MOV_JNO_TXN_FEE.PRIM_AR_ID AS MOV_JNO_TXN_FEE_PRIM_AR_ID,
            	MOV_JNO_TXN_FEE.TXN_BOOK_DT AS MOV_JNO_TXN_FEE_TXN_BOOK_DT,
            	MOV_JNO_TXN_FEE.TXN_CCY_AMT AS MOV_JNO_TXN_FEE_TXN_CCY_AMT,
            	MOV_JNO_TXN_FEE.TXN_CCY_CL_CD AS MOV_JNO_TXN_FEE_TXN_CCY_CL_CD,
            	MOV_JNO_TXN_FEE.TXN_RSN_TP_CL_CD AS MOV_JNO_TXN_FEE_TXN_RSN_TP_CL_CD,
            	MOV_JNO_TXN_FEE.LDGR_CCY_AMT AS MOV_JNO_TXN_FEE_LDGR_CCY_AMT,
            	MOV_JNO_TXN_FEE.LDGR_CCY_CL_CD AS MOV_JNO_TXN_FEE_LDGR_CCY_CL_CD,
            	MOV_JNO_TXN_FEE.DATA_DT AS MOV_JNO_TXN_FEE_DATA_DT,
            	MOV_JNO_TXN_FEE.FCY_RK AS MOV_JNO_TXN_FEE_FCY_RK,
            	MOV_JNO_TXN_FEE.TXN_FEE_TXN_CCY_AMT AS MOV_JNO_TXN_FEE_TXN_FEE_TXN_CCY_AMT,
            	MOV_JNO_TXN_FEE.TXN_FEE_CCY_CL_CD AS MOV_JNO_TXN_FEE_TXN_FEE_CCY_CL_CD,
            	MOV_SRT_EWM_EV_X_CL_R.SRC_DL AS MOV_SRT_EWM_EV_X_CL_R_SRC_DL,
            	MOV_SRT_EWM_EV_X_CL_R.EV_ID AS MOV_SRT_EWM_EV_X_CL_R_EV_ID,
            	MOV_SRT_EWM_EV_X_CL_R.CL_CD AS MOV_SRT_EWM_EV_X_CL_R_CL_CD
        FROM
            {{ ref('mov_jno_txn_fee') }} AS MOV_JNO_TXN_FEE
            LEFT OUTER JOIN {{ ref('mov_srt_ewm_ev_x_cl_r') }} AS MOV_SRT_EWM_EV_X_CL_R ON MOV_JNO_TXN_FEE.EV_ID=MOV_SRT_EWM_EV_X_CL_R.EV_ID
            AND MOV_JNO_TXN_FEE.SRC_DL=MOV_SRT_EWM_EV_X_CL_R.SRC_DL 
)

SELECT * FROM jno_ewm_ev_x_cl_r

