
{{config(
  materialized='ephemeral'
)}}

WITH jno_txn_exn AS (
SELECT
            		MOV_JNO_EWM_EV_X_CL_R AS MOV_JNO_EWM_EV_X_CL_R_,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_RK AS MOV_JNO_EWM_EV_X_CL_R_TXN_RK,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_FEE_CMPT_EV_ID AS MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_CMPT_EV_ID,
            	MOV_JNO_EWM_EV_X_CL_R AS MOV_JNO_EWM_EV_X_CL_R_,
            	MOV_JNO_EWM_EV_X_CL_R.SRC_DL AS MOV_JNO_EWM_EV_X_CL_R_SRC_DL,
            	MOV_JNO_EWM_EV_X_CL_R.EV_ID AS MOV_JNO_EWM_EV_X_CL_R_EV_ID,
            	MOV_JNO_EWM_EV_X_CL_R.CL_CD AS MOV_JNO_EWM_EV_X_CL_R_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R.MSTR_SRC_STM_CD AS MOV_JNO_EWM_EV_X_CL_R_MSTR_SRC_STM_CD,
            	MOV_JNO_EWM_EV_X_CL_R.MSTR_SRC_STM_KEY AS MOV_JNO_EWM_EV_X_CL_R_MSTR_SRC_STM_KEY,
            	MOV_JNO_EWM_EV_X_CL_R.VLD_FROM_TMS AS MOV_JNO_EWM_EV_X_CL_R_VLD_FROM_TMS,
            	MOV_JNO_EWM_EV_X_CL_R.VLD_TO_TMS AS MOV_JNO_EWM_EV_X_CL_R_VLD_TO_TMS,
            	MOV_JNO_EWM_EV_X_CL_R.PRIM_AR_ID AS MOV_JNO_EWM_EV_X_CL_R_PRIM_AR_ID,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_BOOK_DT AS MOV_JNO_EWM_EV_X_CL_R_TXN_BOOK_DT,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_CCY_AMT AS MOV_JNO_EWM_EV_X_CL_R_TXN_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_CCY_CL_CD AS MOV_JNO_EWM_EV_X_CL_R_TXN_CCY_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_RSN_TP_CL_CD AS MOV_JNO_EWM_EV_X_CL_R_TXN_RSN_TP_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R.LDGR_CCY_AMT AS MOV_JNO_EWM_EV_X_CL_R_LDGR_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R.LDGR_CCY_CL_CD AS MOV_JNO_EWM_EV_X_CL_R_LDGR_CCY_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R.DATA_DT AS MOV_JNO_EWM_EV_X_CL_R_DATA_DT,
            	MOV_JNO_EWM_EV_X_CL_R.FCY_RK AS MOV_JNO_EWM_EV_X_CL_R_FCY_RK,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_FEE_TXN_CCY_AMT AS MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_TXN_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R.TXN_FEE_CCY_CL_CD AS MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_CCY_CL_CD,
            	MOV_SRT_EWM_EV_TXN_EXN_V AS MOV_SRT_EWM_EV_TXN_EXN_V_,
            	MOV_SRT_EWM_EV_TXN_EXN_V.EV_ID AS MOV_SRT_EWM_EV_TXN_EXN_V_EV_ID,
            	MOV_SRT_EWM_EV_TXN_EXN_V.SRC_DL AS MOV_SRT_EWM_EV_TXN_EXN_V_SRC_DL,
            	MOV_SRT_EWM_EV_TXN_EXN_V.TXN_EXN_EV_ID AS MOV_SRT_EWM_EV_TXN_EXN_V_TXN_EXN_EV_ID,
            	MOV_SRT_EWM_EV_TXN_EXN_V AS MOV_SRT_EWM_EV_TXN_EXN_V_,
            	MOV_SRT_EWM_EV_TXN_EXN_V.SNDR_TO_RCVR_INF AS MOV_SRT_EWM_EV_TXN_EXN_V_SNDR_TO_RCVR_INF,
            	MOV_SRT_EWM_EV_TXN_EXN_V.INT_TXN_CCY_AMT AS MOV_SRT_EWM_EV_TXN_EXN_V_INT_TXN_CCY_AMT,
            	MOV_SRT_EWM_EV_TXN_EXN_V.PNP_TXN_CCY_AMT AS MOV_SRT_EWM_EV_TXN_EXN_V_PNP_TXN_CCY_AMT
        FROM
            {{ ref('mov_jno_ewm_ev_x_cl_r') }} AS MOV_JNO_EWM_EV_X_CL_R
            LEFT OUTER JOIN {{ ref('mov_srt_ewm_ev_txn_exn_v') }} AS MOV_SRT_EWM_EV_TXN_EXN_V ON MOV_SRT_EWM_EV_TXN_EXN_V.EV_ID=MOV_JNO_EWM_EV_X_CL_R.EV_ID
            AND MOV_SRT_EWM_EV_TXN_EXN_V.SRC_DL=MOV_JNO_EWM_EV_X_CL_R.SRC_DL 
)

SELECT * FROM jno_txn_exn

