
{{config(
  materialized='ephemeral'
)}}

WITH mov_txn_consolidated AS (
SELECT
            		MOV_JNO_EWM_EV_X_CL_R_TXN_RK AS TXN_RK,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_CMPT_EV_ID AS TXN_FEE_CMPT_EV_ID,
            	MOV_JNO_EWM_EV_X_CL_R_FCY_RK AS FCY_RK,
            	MOV_SRT_EWM_EV_TXN_EXN_V_TXN_EXN_EV_ID AS TXN_EXN_EV_ID,
            	MOV_JNO_EWM_EV_X_CL_R_SRC_DL AS SRC_DL,
            	MOV_JNO_EWM_EV_X_CL_R_EV_ID AS EV_ID,
            	MOV_JNO_EWM_EV_X_CL_R_MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	MOV_JNO_EWM_EV_X_CL_R_MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	MOV_JNO_EWM_EV_X_CL_R_VLD_FROM_TMS AS VLD_FROM_TMS,
            	MOV_JNO_EWM_EV_X_CL_R_VLD_TO_TMS AS VLD_TO_TMS,
            	MOV_JNO_EWM_EV_X_CL_R_PRIM_AR_ID AS PRIM_AR_ID,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_BOOK_DT AS TXN_BOOK_DT,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_CCY_AMT AS TXN_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_CCY_CL_CD AS TXN_CCY_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_RSN_TP_CL_CD AS TXN_RSN_TP_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R_LDGR_CCY_AMT AS LDGR_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R_LDGR_CCY_CL_CD AS LDGR_CCY_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_TXN_CCY_AMT AS TXN_FEE_TXN_CCY_AMT,
            	MOV_JNO_EWM_EV_X_CL_R_TXN_FEE_CCY_CL_CD AS TXN_FEE_CCY_CL_CD,
            	MOV_JNO_EWM_EV_X_CL_R_CL_CD AS CL_CD,
            	MOV_SRT_EWM_EV_TXN_EXN_V_SNDR_TO_RCVR_INF AS SNDR_TO_RCVR_INF,
            	MOV_SRT_EWM_EV_TXN_EXN_V_INT_TXN_CCY_AMT AS INT_TXN_CCY_AMT,
            	MOV_SRT_EWM_EV_TXN_EXN_V_PNP_TXN_CCY_AMT AS PNP_TXN_CCY_AMT
        FROM
            {{ ref('jno_txn_exn') }} AS JNO_TXN_EXN 
)

SELECT * FROM mov_txn_consolidated

