
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_ev_txn AS (
SELECT
            		REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.TXN_RK AS TXN_RK,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.SRC_DL AS SRC_DL,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.EV_ID AS EV_ID,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.MSTR_SRC_STM_CD AS MSTR_SRC_STM_CD,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.MSTR_SRC_STM_KEY AS MSTR_SRC_STM_KEY,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.VLD_FROM_TMS AS VLD_FROM_TMS,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.VLD_TO_TMS AS VLD_TO_TMS,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.PRIM_AR_ID AS PRIM_AR_ID,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.TXN_BOOK_DT AS TXN_BOOK_DT,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.TXN_CCY_AMT AS TXN_CCY_AMT,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.TXN_CCY_CL_CD AS TXN_CCY_CL_CD,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.TXN_RSN_TP_CL_CD AS TXN_RSN_TP_CL_CD,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.LDGR_CCY_AMT AS LDGR_CCY_AMT,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.LDGR_CCY_CL_CD AS LDGR_CCY_CL_CD,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.DATA_DT AS DATA_DT,
            	REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION.FCY_RK AS FCY_RK
        FROM
            {{ ref('rea_ewm_mdm_stage_txn_fcy_rk_union') }} AS REA_EWM_MDM_STAGE_TXN_FCY_RK_UNION
        ORDER BY
            EV_ID ASC,
            SRC_DL ASC 
)

SELECT * FROM mov_srt_ev_txn

