
{{config(
  materialized='ephemeral'
)}}

WITH jni_mstr_cr_fcy_rk AS (
SELECT
            		MOV_SRT_OBJ_AR_ID AS MOV_SRT_OBJ_AR_ID_,
            	MOV_SRT_OBJ_AR_ID.OBJ_AR_ID AS MOV_SRT_OBJ_AR_ID_OBJ_AR_ID,
            	MOV_SRT_OBJ_AR_ID.SRC_DL AS MOV_SRT_OBJ_AR_ID_SRC_DL,
            	MOV_SRT_OBJ_AR_ID.SUBJ_AR_ID AS MOV_SRT_OBJ_AR_ID_SUBJ_AR_ID,
            	MOV_SRT_OBJ_AR_ID AS MOV_SRT_OBJ_AR_ID_,
            	MOV_SRT_OBJ_AR_ID.EV_ID AS MOV_SRT_OBJ_AR_ID_EV_ID,
            	MOV_SRT_OBJ_AR_ID.MSTR_SRC_STM_CD AS MOV_SRT_OBJ_AR_ID_MSTR_SRC_STM_CD,
            	MOV_SRT_OBJ_AR_ID.MSTR_SRC_STM_KEY AS MOV_SRT_OBJ_AR_ID_MSTR_SRC_STM_KEY,
            	MOV_SRT_OBJ_AR_ID.VLD_FROM_TMS AS MOV_SRT_OBJ_AR_ID_VLD_FROM_TMS,
            	MOV_SRT_OBJ_AR_ID.VLD_TO_TMS AS MOV_SRT_OBJ_AR_ID_VLD_TO_TMS,
            	MOV_SRT_OBJ_AR_ID.PRIM_AR_ID AS MOV_SRT_OBJ_AR_ID_PRIM_AR_ID,
            	MOV_SRT_OBJ_AR_ID.TXN_BOOK_DT AS MOV_SRT_OBJ_AR_ID_TXN_BOOK_DT,
            	MOV_SRT_OBJ_AR_ID.TXN_CCY_AMT AS MOV_SRT_OBJ_AR_ID_TXN_CCY_AMT,
            	MOV_SRT_OBJ_AR_ID.TXN_CCY_CL_CD AS MOV_SRT_OBJ_AR_ID_TXN_CCY_CL_CD,
            	MOV_SRT_OBJ_AR_ID.TXN_RSN_TP_CL_CD AS MOV_SRT_OBJ_AR_ID_TXN_RSN_TP_CL_CD,
            	MOV_SRT_OBJ_AR_ID.LDGR_CCY_AMT AS MOV_SRT_OBJ_AR_ID_LDGR_CCY_AMT,
            	MOV_SRT_OBJ_AR_ID.LDGR_CCY_CL_CD AS MOV_SRT_OBJ_AR_ID_LDGR_CCY_CL_CD,
            	MOV_SRT_EWM_STG_FCY_TXN AS MOV_SRT_EWM_STG_FCY_TXN_,
            	MOV_SRT_EWM_STG_FCY_TXN.OBJ_AR_ID AS MOV_SRT_EWM_STG_FCY_TXN_OBJ_AR_ID,
            	MOV_SRT_EWM_STG_FCY_TXN.FCY_RK AS MOV_SRT_EWM_STG_FCY_TXN_FCY_RK,
            	MOV_SRT_EWM_STG_FCY_TXN.DATA_DT AS MOV_SRT_EWM_STG_FCY_TXN_DATA_DT,
            	MOV_SRT_EWM_STG_FCY_TXN AS MOV_SRT_EWM_STG_FCY_TXN_,
            	MOV_SRT_EWM_STG_FCY_TXN.SRC_DL AS MOV_SRT_EWM_STG_FCY_TXN_SRC_DL
        FROM
            {{ ref('mov_srt_obj_ar_id_m1') }} AS MOV_SRT_OBJ_AR_ID
            INNER JOIN {{ ref('mov_srt_ewm_stg_fcy_txn_m2') }} AS MOV_SRT_EWM_STG_FCY_TXN ON MOV_SRT_EWM_STG_FCY_TXN.SRC_DL=MOV_SRT_OBJ_AR_ID.SRC_DL
            AND MOV_SRT_EWM_STG_FCY_TXN.OBJ_AR_ID=MOV_SRT_OBJ_AR_ID.OBJ_AR_ID 
)

SELECT * FROM jni_mstr_cr_fcy_rk

