
{{config(
  materialized='ephemeral'
)}}

WITH jno_ip_v AS (
SELECT
            		MOV_SRT_AR_X_IP_R_ROU.IP_ID AS MOV_SRT_AR_X_IP_R_ROU_IP_ID,
            	MOV_SRT_AR_X_IP_R_ROU.CST_VORTEX_ID AS MOV_SRT_AR_X_IP_R_ROU_CST_VORTEX_ID,
            	MOV_SRT_AR_X_IP_R_ROU.GRID AS MOV_SRT_AR_X_IP_R_ROU_GRID,
            	MOV_SRT_AR_X_IP_R_ROU.SRC_DL AS MOV_SRT_AR_X_IP_R_ROU_SRC_DL,
            	MOV_SRT_EWM_IP.IP_ID AS MOV_SRT_EWM_IP_IP_ID,
            	MOV_SRT_EWM_IP.CST_RK AS MOV_SRT_EWM_IP_CST_RK,
            	MOV_SRT_EWM_IP.VLD_TO_TMS AS MOV_SRT_EWM_IP_VLD_TO_TMS,
            	MOV_SRT_EWM_IP.SRC_DL AS MOV_SRT_EWM_IP_SRC_DL,
            	MOV_SRT_EWM_IP.MSTR_SRC_STM_CD AS MOV_SRT_EWM_IP_MSTR_SRC_STM_CD,
            	MOV_SRT_EWM_IP.MSTR_SRC_STM_KEY AS MOV_SRT_EWM_IP_MSTR_SRC_STM_KEY,
            	MOV_SRT_EWM_IP.VLD_FROM_TMS AS MOV_SRT_EWM_IP_VLD_FROM_TMS
        FROM
            {{ ref('mov_srt_ar_x_ip_r_rou') }} AS MOV_SRT_AR_X_IP_R_ROU
            LEFT OUTER JOIN {{ ref('mov_srt_ewm_ip') }} AS MOV_SRT_EWM_IP ON MOV_SRT_EWM_IP.IP_ID=MOV_SRT_AR_X_IP_R_ROU.IP_ID
            AND MOV_SRT_EWM_IP.SRC_DL=MOV_SRT_AR_X_IP_R_ROU.SRC_DL 
)

SELECT * FROM jno_ip_v

