---
sources:

- name: "DM_MPSCR"
  description: "Source tables"
  database: "cognizant-pocngdap-01"
  schema: "DM_MPSCR"
  tables:
  - name: "BMG_T24_CUSTOMER_DP"
  - name: "CL_CV_V"
  - name: "_ATTBLB_BMG_T24_CUSTOMER_DP_ATTBLE_"
  - name: "_ATTBLB_BMG_T24_CUSTOMER_DP_ATTBLE___STBL_"
