sources:

- name: "DM_MPSCR"
  description: "Source tables"
  database: "cognizant-pocngdap-01"
  schema: "DM_MPSCR"
  tables:
  - name: "EWM_MDM_STAGE_CRDT_RISK_RATING"
  - name: "MDM_CREDIT_RISK_RATING"
  - name: "EWM_IP_ORG_V"
  - name: "EWM_AR_FCY_AR_V"
  - name: "EWM_IP_X_CL_RTG_R"
  - name: "EWM_AR_FCY_AR_DRV_V"
  - name: "EWM_IP_IDV_V"
  - name: "EWM_CL_JCOG_X_CL_RTG_R"
  - name: "EWM_CL_JCOG_V"
  - name: "EWM_AR_X_CL_RTG_R"
  - name: "MDM_CREDIT_RISK_RATING_UPD_DEL"
  - name: "EWM_IP_ALT_IDENTN_M"
  - name: "EWM_IP_X_CL_R"
  - name: "EWM_IP_X_CL_LC_ST_R"
  - name: "EWM_AR_X_IP_R"

