---
sources:

- name: "xg_ps_rdb_dm_mpscr_database_xg_rdb_dm_schema_mpscr"
  description: "Source tables"
  database: "<DATABASE NAME>"
  schema: "xg_ps_rdb_dm_mpscr_database_xg_rdb_dm_schema_mpscr"
  tables:
  - name: "ewm_ip_org_v"
  - name: "ewm_ip_alt_identn_m"
  - name: "ewm_ip_x_cl_r"
  - name: "ewm_ip_x_cl_lc_st_r"
  - name: "ewm_ar_x_ip_r"
  - name: "ewm_ip_idv_v"
  - name: "__amp__xg_pm_tgttbl"
