---
sources:

- name: "DM_MPSCR"
  description: "Source tables"
  database: "cognizant-pocngdap-01"
  schema: "DM_MPSCR"
  tables:
  - name: "EWM_AR_X_IP_R"
  - name: "EWM_IP_ORG_V"
  - name: "EWM_IP_ALT_IDENTN_M"
  - name: "EWM_IP_X_CL_LC_ST_R"
  - name: "EWM_IP_IDV_V"
  - name: "EWM_IP_X_CL_R"
  - name: "{{var('xg_pm_tgttbl')}}"
