---
sources:

- name: "DM_MPSCR"
  description: "Source tables"
  database: "cognizant-pocngdap-01"
  schema: "DM_MPSCR"
  tables:
  - name: "EWM_AR_FCY_AR_V"
  - name: "{{var('xg_pm_tgttbl')}}"
  - name: "EWM_AR_FCY_AR_DRV_V"
  - name: "EWM_MDM_STAGE_FACILITY"
  - name: "EWM_AR_X_IP_R"
  - name: "EWM_IP_X_EV_R"
  - name: "EWM_MDM_STAGE_FCY_AR_TP"
  - name: "EWM_EV_JDCL_EV_V"
  - name: "EWM_MDM_STAGE_FCY_AR"
  - name: "EWM_AR_X_AR_R"
  - name: "EWM_AR_X_CL_FNC_ST_R"
  - name: "EWM_IP_X_CL_FNC_ST_R"
  - name: "EWM_AR_SCR_TRD_TXN_V"
  - name: "EWM_AR_SWAP_TXN_V"
  - name: "EWM_AR_LOAN_AR_V"
  - name: "EWM_AR_RPRCH_AGRM_TXN_V"
  - name: "EWM_AR_RCVB_FNC_AR_V"
  - name: "EWM_AR_DEP_AR_V"
  - name: "EWM_AR_LOC_AR_V"
  - name: "EWM_AR_FX_TXN_V"
  - name: "EWM_AR_FWD_TXN_V"
  - name: "EWM_AR_LSE_AR_V"
  - name: "EWM_AR_OPT_TXN_V"
  - name: "EWM_AR_MRTG_AR_V"
  - name: "EWM_AR_LTR_OF_GNT_AR_V"
  - name: "EWM_AR_LTROC_AR_V"
  - name: "EWM_MDM_STAGE_FCY_AR_IP_JDCL"
  - name: "EWM_AR_IDENTN_M"
