---
sources:

- name: "DM_MPSCR"
  description: "Source tables"
  database: "cognizant-pocngdap-01"
  schema: "DM_MPSCR"
  tables:
  - name: "EWM_MDM_STAGE_TRANSACTION_FCY"
  - name: "EWM_EV_TXN_V"
  - name: "{{var('xg_pm_tgttbl')}}"
  - name: "EWM_MDM_STAGE_TXN_FCY_RK_MASTER"
  - name: "EWM_MDM_STAGE_TXN_FCY_RK_AGRMT"
  - name: "EWM_MDM_STAGE_TXN_FCY_RK_DIRECT"
  - name: "EWM_AR_FWD_TXN_V"
  - name: "EWM_AR_FX_TXN_V"
  - name: "EWM_AR_OPT_TXN_V"
  - name: "EWM_AR_RPRCH_AGRM_TXN_V"
  - name: "EWM_AR_SCR_TRD_TXN_V"
  - name: "EWM_AR_SWAP_TXN_V"
  - name: "EWM_AR_FCY_AR_DRV_V"
  - name: "EWM_AR_FCY_AR_V"
  - name: "EWM_AR_MSTR_CR_AR_V"
  - name: "EWM_AR_X_AR_R"
  - name: "EWM_MDM_STAGE_AR_TX_TRANSACTN"
  - name: "EWM_MDM_STAGE_AR_TRANSACTION"
  - name: "EWM_MDM_STAGE_TX_TRANSACTION"
  - name: "EWM_MDM_STAGE_TXN_FCY_RK_UNION"
  - name: "EWM_EV_TXN_EXN_V"
  - name: "EWM_EV_X_CL_R"
  - name: "EWM_EV_TXN_FEE_CMPT_M"
  - name: "EWM_AR_DEP_AR_V"
  - name: "EWM_AR_LOAN_AR_V"
  - name: "EWM_AR_LOC_AR_V"
  - name: "EWM_AR_LSE_AR_V"
  - name: "EWM_AR_LTR_OF_GNT_AR_V"
  - name: "EWM_AR_LTROC_AR_V"
  - name: "EWM_AR_MRTG_AR_V"
  - name: "EWM_AR_RCVB_FNC_AR_V"
