
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_spsdg_ar_drv AS (
SELECT
            		MOV_SRT_FCY_SPSDG_AR AS MOV_SRT_FCY_SPSDG_AR_,
            	MOV_SRT_FCY_SPSDG_AR.SPSDG_FCY_DT AS MOV_SRT_FCY_SPSDG_AR_SPSDG_FCY_DT,
            	MOV_SRT_FCY_SPSDG_AR AS MOV_SRT_FCY_SPSDG_AR_,
            	MOV_SRT_FCY_SPSDG_AR.SRC_DL AS MOV_SRT_FCY_SPSDG_AR_SRC_DL,
            	MOV_SRT_FCY_SPSDG_AR.DATA_DT AS MOV_SRT_FCY_SPSDG_AR_DATA_DT,
            	MOV_SRT_FCY_SPSDG_AR.SYS_VLD_FROM_TMS AS MOV_SRT_FCY_SPSDG_AR_SYS_VLD_FROM_TMS,
            	MOV_SRT_FCY_SPSDG_AR.SYS_VLD_TO_TMS AS MOV_SRT_FCY_SPSDG_AR_SYS_VLD_TO_TMS,
            	MOV_SRT_FCY_SPSDG_AR.SRC_STM_ID AS MOV_SRT_FCY_SPSDG_AR_SRC_STM_ID,
            	MOV_SRT_FCY_SPSDG_AR.FCY_ID AS MOV_SRT_FCY_SPSDG_AR_FCY_ID,
            	MOV_SRT_FCY_SPSDG_AR.FCY_RK AS MOV_SRT_FCY_SPSDG_AR_FCY_RK,
            	MOV_SRT_FCY_SPSDG_AR.AR_ID AS MOV_SRT_FCY_SPSDG_AR_AR_ID,
            	MOV_SRT_FCY_SPSDG_AR.FCY_AR_TP AS MOV_SRT_FCY_SPSDG_AR_FCY_AR_TP,
            	MOV_SRT_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_FCY AS MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_AR.OUT_OF_COURT_WRKOUT_FCY AS MOV_SRT_FCY_SPSDG_AR_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_FCY_SPSDG_AR.CR_OBLG_DFLTD AS MOV_SRT_FCY_SPSDG_AR_CR_OBLG_DFLTD,
            	MOV_SRT_FCY_SPSDG_AR.UNDRL_AR_ID AS MOV_SRT_FCY_SPSDG_AR_UNDRL_AR_ID,
            	MOV_SRT_FCY_SPSDG_AR.SUBJ_AR_ID AS MOV_SRT_FCY_SPSDG_AR_SUBJ_AR_ID,
            	MOV_SRT_FCY_AR_DRV AS MOV_SRT_FCY_AR_DRV_,
            	MOV_SRT_FCY_AR_DRV.SRC_DL AS MOV_SRT_FCY_AR_DRV_SRC_DL,
            	MOV_SRT_FCY_AR_DRV.SUBJ_AR_ID AS MOV_SRT_FCY_AR_DRV_SUBJ_AR_ID,
            	MOV_SRT_FCY_AR_DRV.SPSDG_FCY_RK AS MOV_SRT_FCY_AR_DRV_SPSDG_FCY_RK,
            	MOV_SRT_FCY_AR_DRV AS MOV_SRT_FCY_AR_DRV_
        FROM
            {{ ref('mov_srt_fcy_spsdg_ar') }} AS MOV_SRT_FCY_SPSDG_AR
            LEFT OUTER JOIN {{ ref('mov_srt_fcy_ar_drv') }} AS MOV_SRT_FCY_AR_DRV ON MOV_SRT_FCY_AR_DRV.SRC_DL=MOV_SRT_FCY_SPSDG_AR.SRC_DL
            AND MOV_SRT_FCY_AR_DRV.SUBJ_AR_ID=MOV_SRT_FCY_SPSDG_AR.SUBJ_AR_ID 
)

SELECT * FROM jno_fcy_spsdg_ar_drv

