
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_hghst_fcy_ar AS (
SELECT
            		MOV_SRT_FCY_AR_HGHST.SRC_DL AS MOV_SRT_FCY_AR_HGHST_SRC_DL,
            	MOV_SRT_FCY_AR_HGHST.HIGHEST_FCY_ID AS MOV_SRT_FCY_AR_HGHST_HIGHEST_FCY_ID,
            	MOV_SRT_FCY_AR_HGHST.HIGHEST_FCY_RK AS MOV_SRT_FCY_AR_HGHST_HIGHEST_FCY_RK,
            	MOV_SRT_HGST_FCY_AR.SPSDG_FCY_DT AS MOV_SRT_HGST_FCY_AR_SPSDG_FCY_DT,
            	MOV_SRT_HGST_FCY_AR.SPSDG_FCY_RK AS MOV_SRT_HGST_FCY_AR_SPSDG_FCY_RK,
            	MOV_SRT_HGST_FCY_AR.HIGHER_FCY_ID AS MOV_SRT_HGST_FCY_AR_HIGHER_FCY_ID,
            	MOV_SRT_HGST_FCY_AR.HIGHEST_FCY_ID AS MOV_SRT_HGST_FCY_AR_HIGHEST_FCY_ID,
            	MOV_SRT_HGST_FCY_AR.LEAF AS MOV_SRT_HGST_FCY_AR_LEAF,
            	MOV_SRT_HGST_FCY_AR.HIGHER_FCY_RK AS MOV_SRT_HGST_FCY_AR_HIGHER_FCY_RK,
            	MOV_SRT_HGST_FCY_AR.SRC_DL AS MOV_SRT_HGST_FCY_AR_SRC_DL,
            	MOV_SRT_HGST_FCY_AR.DATA_DT AS MOV_SRT_HGST_FCY_AR_DATA_DT,
            	MOV_SRT_HGST_FCY_AR.SYS_VLD_FROM_TMS AS MOV_SRT_HGST_FCY_AR_SYS_VLD_FROM_TMS,
            	MOV_SRT_HGST_FCY_AR.SYS_VLD_TO_TMS AS MOV_SRT_HGST_FCY_AR_SYS_VLD_TO_TMS,
            	MOV_SRT_HGST_FCY_AR.SRC_STM_ID AS MOV_SRT_HGST_FCY_AR_SRC_STM_ID,
            	MOV_SRT_HGST_FCY_AR.FCY_ID AS MOV_SRT_HGST_FCY_AR_FCY_ID,
            	MOV_SRT_HGST_FCY_AR.FCY_RK AS MOV_SRT_HGST_FCY_AR_FCY_RK,
            	MOV_SRT_HGST_FCY_AR.AR_ID AS MOV_SRT_HGST_FCY_AR_AR_ID,
            	MOV_SRT_HGST_FCY_AR.FCY_AR_TP AS MOV_SRT_HGST_FCY_AR_FCY_AR_TP,
            	MOV_SRT_HGST_FCY_AR.COURT_CTRLD_WRKOUT_FCY AS MOV_SRT_HGST_FCY_AR_COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_HGST_FCY_AR.OUT_OF_COURT_WRKOUT_FCY AS MOV_SRT_HGST_FCY_AR_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_HGST_FCY_AR.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_SRT_HGST_FCY_AR_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_HGST_FCY_AR.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_SRT_HGST_FCY_AR_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_HGST_FCY_AR.CR_OBLG_DFLTD AS MOV_SRT_HGST_FCY_AR_CR_OBLG_DFLTD,
            	MOV_SRT_HGST_FCY_AR.UNDRL_AR_ID AS MOV_SRT_HGST_FCY_AR_UNDRL_AR_ID
        FROM
            {{ ref('mov_srt_fcy_ar_hghst') }} AS MOV_SRT_FCY_AR_HGHST
            LEFT OUTER JOIN {{ ref('mov_srt_hgst_fcy_ar') }} AS MOV_SRT_HGST_FCY_AR ON MOV_SRT_HGST_FCY_AR.SRC_DL=MOV_SRT_FCY_AR_HGHST.SRC_DL
            AND MOV_SRT_HGST_FCY_AR.HIGHEST_FCY_ID=MOV_SRT_FCY_AR_HGHST.HIGHEST_FCY_ID 
)

SELECT * FROM jno_fcy_hghst_fcy_ar

