
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_ar_identn AS (
SELECT
            		MOV_CY_AR_LWST_HGHST.SPSDG_FCY_DT AS MOV_CY_AR_LWST_HGHST_SPSDG_FCY_DT,
            	MOV_CY_AR_LWST_HGHST.SPSDG_FCY_RK AS MOV_CY_AR_LWST_HGHST_SPSDG_FCY_RK,
            	MOV_CY_AR_LWST_HGHST.HLEAF AS MOV_CY_AR_LWST_HGHST_HLEAF,
            	MOV_CY_AR_LWST_HGHST.HIGHER_FCY_RK AS MOV_CY_AR_LWST_HGHST_HIGHER_FCY_RK,
            	MOV_CY_AR_LWST_HGHST.HIGHEST_FCY_RK AS MOV_CY_AR_LWST_HGHST_HIGHEST_FCY_RK,
            	MOV_CY_AR_LWST_HGHST.HIGHEST_FCY_IN_HRY AS MOV_CY_AR_LWST_HGHST_HIGHEST_FCY_IN_HRY,
            	MOV_CY_AR_LWST_HGHST.SRC_DL AS MOV_CY_AR_LWST_HGHST_SRC_DL,
            	MOV_CY_AR_LWST_HGHST.DATA_DT AS MOV_CY_AR_LWST_HGHST_DATA_DT,
            	MOV_CY_AR_LWST_HGHST.SYS_VLD_FROM_TMS AS MOV_CY_AR_LWST_HGHST_SYS_VLD_FROM_TMS,
            	MOV_CY_AR_LWST_HGHST.SYS_VLD_TO_TMS AS MOV_CY_AR_LWST_HGHST_SYS_VLD_TO_TMS,
            	MOV_CY_AR_LWST_HGHST.SRC_STM_ID AS MOV_CY_AR_LWST_HGHST_SRC_STM_ID,
            	MOV_CY_AR_LWST_HGHST.FCY_ID AS MOV_CY_AR_LWST_HGHST_FCY_ID,
            	MOV_CY_AR_LWST_HGHST.FCY_RK AS MOV_CY_AR_LWST_HGHST_FCY_RK,
            	MOV_CY_AR_LWST_HGHST.AR_ID AS MOV_CY_AR_LWST_HGHST_AR_ID,
            	MOV_CY_AR_LWST_HGHST.FCY_AR_TP AS MOV_CY_AR_LWST_HGHST_FCY_AR_TP,
            	MOV_CY_AR_LWST_HGHST.COURT_CTRLD_WRKOUT_FCY AS MOV_CY_AR_LWST_HGHST_COURT_CTRLD_WRKOUT_FCY,
            	MOV_CY_AR_LWST_HGHST.OUT_OF_COURT_WRKOUT_FCY AS MOV_CY_AR_LWST_HGHST_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_CY_AR_LWST_HGHST.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_CY_AR_LWST_HGHST_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_CY_AR_LWST_HGHST.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_CY_AR_LWST_HGHST_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_CY_AR_LWST_HGHST.CR_OBLG_DFLTD AS MOV_CY_AR_LWST_HGHST_CR_OBLG_DFLTD,
            	MOV_CY_AR_LWST_HGHST.UNDRL_AR_ID AS MOV_CY_AR_LWST_HGHST_UNDRL_AR_ID,
            	MOV_SRT_MPS_AR_IDENTN.AR_ID AS MOV_SRT_MPS_AR_IDENTN_AR_ID,
            	MOV_SRT_MPS_AR_IDENTN.AR_IDENTN_NM AS MOV_SRT_MPS_AR_IDENTN_AR_IDENTN_NM,
            	MOV_SRT_MPS_AR_IDENTN.SRC_DL AS MOV_SRT_MPS_AR_IDENTN_SRC_DL
        FROM
            {{ ref('mov_cy_ar_lwst_hghst') }} AS MOV_CY_AR_LWST_HGHST
            LEFT OUTER JOIN {{ ref('mov_srt_mps_ar_identn') }} AS MOV_SRT_MPS_AR_IDENTN ON MOV_CY_AR_LWST_HGHST.SRC_DL=MOV_SRT_MPS_AR_IDENTN.SRC_DL
            AND MOV_CY_AR_LWST_HGHST.AR_ID=MOV_SRT_MPS_AR_IDENTN.AR_ID 
)

SELECT * FROM jno_fcy_ar_identn

