
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_hgr_hst_low_fcy AS (
SELECT
            		MOV_SRT_AR_X_AR_R_HGR.SRC_DL AS MOV_SRT_AR_X_AR_R_HGR_SRC_DL,
            	MOV_SRT_AR_X_AR_R_HGR.AR_ID AS MOV_SRT_AR_X_AR_R_HGR_AR_ID,
            	MOV_SRT_AR_X_AR_R_HGR.HIGHER_FCY_ID AS MOV_SRT_AR_X_AR_R_HGR_HIGHER_FCY_ID,
            	MOV_SRT_AR_X_AR_R_HGR.HIGHEST_FCY_ID AS MOV_SRT_AR_X_AR_R_HGR_HIGHEST_FCY_ID,
            	MOV_SRT_AR_X_AR_R_HGR.LEAF AS MOV_SRT_AR_X_AR_R_HGR_LEAF,
            	MOV_SRT_FCY_SPSDG_DRV.SPSDG_FCY_DT AS MOV_SRT_FCY_SPSDG_DRV_SPSDG_FCY_DT,
            	MOV_SRT_FCY_SPSDG_DRV.SPSDG_FCY_RK AS MOV_SRT_FCY_SPSDG_DRV_SPSDG_FCY_RK,
            	MOV_SRT_FCY_SPSDG_DRV.SRC_DL AS MOV_SRT_FCY_SPSDG_DRV_SRC_DL,
            	MOV_SRT_FCY_SPSDG_DRV.DATA_DT AS MOV_SRT_FCY_SPSDG_DRV_DATA_DT,
            	MOV_SRT_FCY_SPSDG_DRV.SYS_VLD_FROM_TMS AS MOV_SRT_FCY_SPSDG_DRV_SYS_VLD_FROM_TMS,
            	MOV_SRT_FCY_SPSDG_DRV.SYS_VLD_TO_TMS AS MOV_SRT_FCY_SPSDG_DRV_SYS_VLD_TO_TMS,
            	MOV_SRT_FCY_SPSDG_DRV.SRC_STM_ID AS MOV_SRT_FCY_SPSDG_DRV_SRC_STM_ID,
            	MOV_SRT_FCY_SPSDG_DRV.FCY_ID AS MOV_SRT_FCY_SPSDG_DRV_FCY_ID,
            	MOV_SRT_FCY_SPSDG_DRV.FCY_RK AS MOV_SRT_FCY_SPSDG_DRV_FCY_RK,
            	MOV_SRT_FCY_SPSDG_DRV.AR_ID AS MOV_SRT_FCY_SPSDG_DRV_AR_ID,
            	MOV_SRT_FCY_SPSDG_DRV.FCY_AR_TP AS MOV_SRT_FCY_SPSDG_DRV_FCY_AR_TP,
            	MOV_SRT_FCY_SPSDG_DRV.COURT_CTRLD_WRKOUT_FCY AS MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_DRV.OUT_OF_COURT_WRKOUT_FCY AS MOV_SRT_FCY_SPSDG_DRV_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_DRV.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_FCY_SPSDG_DRV.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_FCY_SPSDG_DRV.CR_OBLG_DFLTD AS MOV_SRT_FCY_SPSDG_DRV_CR_OBLG_DFLTD,
            	MOV_SRT_FCY_SPSDG_DRV.UNDRL_AR_ID AS MOV_SRT_FCY_SPSDG_DRV_UNDRL_AR_ID
        FROM
            {{ ref('mov_srt_ar_x_ar_r_hgr') }} AS MOV_SRT_AR_X_AR_R_HGR
            LEFT OUTER JOIN {{ ref('mov_srt_fcy_spsdg_drv') }} AS MOV_SRT_FCY_SPSDG_DRV ON MOV_SRT_FCY_SPSDG_DRV.SRC_DL=MOV_SRT_AR_X_AR_R_HGR.SRC_DL
            AND MOV_SRT_FCY_SPSDG_DRV.AR_ID=MOV_SRT_AR_X_AR_R_HGR.AR_ID 
)

SELECT * FROM jno_fcy_hgr_hst_low_fcy

