
{{config(
  materialized='ephemeral'
)}}

WITH jno_fcy_hghr_fcy_ar AS (
SELECT
            		MOV_SRT_HGR_HST_FCY AS MOV_SRT_HGR_HST_FCY_,
            	MOV_SRT_HGR_HST_FCY.SPSDG_FCY_DT AS MOV_SRT_HGR_HST_FCY_SPSDG_FCY_DT,
            	MOV_SRT_HGR_HST_FCY.SPSDG_FCY_RK AS MOV_SRT_HGR_HST_FCY_SPSDG_FCY_RK,
            	MOV_SRT_HGR_HST_FCY.HIGHER_FCY_ID AS MOV_SRT_HGR_HST_FCY_HIGHER_FCY_ID,
            	MOV_SRT_HGR_HST_FCY.HIGHEST_FCY_ID AS MOV_SRT_HGR_HST_FCY_HIGHEST_FCY_ID,
            	MOV_SRT_HGR_HST_FCY.LEAF AS MOV_SRT_HGR_HST_FCY_LEAF,
            	MOV_SRT_HGR_HST_FCY AS MOV_SRT_HGR_HST_FCY_,
            	MOV_SRT_HGR_HST_FCY.SRC_DL AS MOV_SRT_HGR_HST_FCY_SRC_DL,
            	MOV_SRT_HGR_HST_FCY.DATA_DT AS MOV_SRT_HGR_HST_FCY_DATA_DT,
            	MOV_SRT_HGR_HST_FCY.SYS_VLD_FROM_TMS AS MOV_SRT_HGR_HST_FCY_SYS_VLD_FROM_TMS,
            	MOV_SRT_HGR_HST_FCY.SYS_VLD_TO_TMS AS MOV_SRT_HGR_HST_FCY_SYS_VLD_TO_TMS,
            	MOV_SRT_HGR_HST_FCY.SRC_STM_ID AS MOV_SRT_HGR_HST_FCY_SRC_STM_ID,
            	MOV_SRT_HGR_HST_FCY.FCY_ID AS MOV_SRT_HGR_HST_FCY_FCY_ID,
            	MOV_SRT_HGR_HST_FCY.FCY_RK AS MOV_SRT_HGR_HST_FCY_FCY_RK,
            	MOV_SRT_HGR_HST_FCY.AR_ID AS MOV_SRT_HGR_HST_FCY_AR_ID,
            	MOV_SRT_HGR_HST_FCY.FCY_AR_TP AS MOV_SRT_HGR_HST_FCY_FCY_AR_TP,
            	MOV_SRT_HGR_HST_FCY.COURT_CTRLD_WRKOUT_FCY AS MOV_SRT_HGR_HST_FCY_COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_HGR_HST_FCY.OUT_OF_COURT_WRKOUT_FCY AS MOV_SRT_HGR_HST_FCY_OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_HGR_HST_FCY.COURT_CTRLD_WRKOUT_FILL_DT AS MOV_SRT_HGR_HST_FCY_COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_HGR_HST_FCY.COURT_CTRLD_WRKOUT_CLS_DT AS MOV_SRT_HGR_HST_FCY_COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_HGR_HST_FCY.CR_OBLG_DFLTD AS MOV_SRT_HGR_HST_FCY_CR_OBLG_DFLTD,
            	MOV_SRT_HGR_HST_FCY.UNDRL_AR_ID AS MOV_SRT_HGR_HST_FCY_UNDRL_AR_ID,
            	MOV_SRT_FCY_AR_HGR AS MOV_SRT_FCY_AR_HGR_,
            	MOV_SRT_FCY_AR_HGR.SRC_DL AS MOV_SRT_FCY_AR_HGR_SRC_DL,
            	MOV_SRT_FCY_AR_HGR.HIGHER_FCY_ID AS MOV_SRT_FCY_AR_HGR_HIGHER_FCY_ID,
            	MOV_SRT_FCY_AR_HGR.HIGHER_FCY_RK AS MOV_SRT_FCY_AR_HGR_HIGHER_FCY_RK,
            	MOV_SRT_FCY_AR_HGR AS MOV_SRT_FCY_AR_HGR_
        FROM
            {{ ref('mov_srt_hgr_hst_fcy') }} AS MOV_SRT_HGR_HST_FCY
            LEFT OUTER JOIN {{ ref('mov_srt_fcy_ar_hgr') }} AS MOV_SRT_FCY_AR_HGR ON MOV_SRT_FCY_AR_HGR.SRC_DL=MOV_SRT_HGR_HST_FCY.SRC_DL
            AND MOV_SRT_FCY_AR_HGR.HIGHER_FCY_ID=MOV_SRT_HGR_HST_FCY.HIGHER_FCY_ID 
)

SELECT * FROM jno_fcy_hghr_fcy_ar

