
{{config(
  materialized='ephemeral'
)}}

WITH mov_fcy_spsdg_ar_drv AS (
SELECT
            		MOV_SRT_FCY_SPSDG_AR_SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_SRT_FCY_AR_DRV_SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_SRT_FCY_SPSDG_AR_SRC_DL AS SRC_DL,
            	MOV_SRT_FCY_SPSDG_AR_DATA_DT AS DATA_DT,
            	MOV_SRT_FCY_SPSDG_AR_SYS_VLD_FROM_TMS AS SYS_VLD_FROM_TMS,
            	MOV_SRT_FCY_SPSDG_AR_SYS_VLD_TO_TMS AS SYS_VLD_TO_TMS,
            	MOV_SRT_FCY_SPSDG_AR_SRC_STM_ID AS SRC_STM_ID,
            	MOV_SRT_FCY_SPSDG_AR_FCY_ID AS FCY_ID,
            	MOV_SRT_FCY_SPSDG_AR_FCY_RK AS FCY_RK,
            	MOV_SRT_FCY_SPSDG_AR_AR_ID AS AR_ID,
            	MOV_SRT_FCY_SPSDG_AR_FCY_AR_TP AS FCY_AR_TP,
            	MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_AR_OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_FCY_SPSDG_AR_COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_FCY_SPSDG_AR_CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_SRT_FCY_SPSDG_AR_UNDRL_AR_ID AS UNDRL_AR_ID
        FROM
            {{ ref('jno_fcy_spsdg_ar_drv') }} AS JNO_FCY_SPSDG_AR_DRV 
)

SELECT * FROM mov_fcy_spsdg_ar_drv

