
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_fcy_spsdg_ar AS (
SELECT
            		MOV_FCY_SPSDG_AR.SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_FCY_SPSDG_AR.SRC_DL AS SRC_DL,
            	MOV_FCY_SPSDG_AR.DATA_DT AS DATA_DT,
            	MOV_FCY_SPSDG_AR.SYS_VLD_FROM_TMS AS SYS_VLD_FROM_TMS,
            	MOV_FCY_SPSDG_AR.SYS_VLD_TO_TMS AS SYS_VLD_TO_TMS,
            	MOV_FCY_SPSDG_AR.SRC_STM_ID AS SRC_STM_ID,
            	MOV_FCY_SPSDG_AR.FCY_ID AS FCY_ID,
            	MOV_FCY_SPSDG_AR.FCY_RK AS FCY_RK,
            	MOV_FCY_SPSDG_AR.AR_ID AS AR_ID,
            	MOV_FCY_SPSDG_AR.FCY_AR_TP AS FCY_AR_TP,
            	MOV_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_FCY_SPSDG_AR.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_FCY_SPSDG_AR.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_FCY_SPSDG_AR.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_FCY_SPSDG_AR.UNDRL_AR_ID AS UNDRL_AR_ID,
            	MOV_FCY_SPSDG_AR.SUBJ_AR_ID AS SUBJ_AR_ID
        FROM
            {{ ref('mov_fcy_spsdg_ar') }} AS MOV_FCY_SPSDG_AR
        ORDER BY
            SRC_DL ASC,
            SUBJ_AR_ID ASC 
)

SELECT * FROM mov_srt_fcy_spsdg_ar

