
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_hgr_hst_fcy AS (
SELECT
            		MOV_FCY_HGR_HST_LOW_FCY.SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_FCY_HGR_HST_LOW_FCY.SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_FCY_HGR_HST_LOW_FCY.HIGHER_FCY_ID AS HIGHER_FCY_ID,
            	MOV_FCY_HGR_HST_LOW_FCY.HIGHEST_FCY_ID AS HIGHEST_FCY_ID,
            	MOV_FCY_HGR_HST_LOW_FCY.LEAF AS LEAF,
            	MOV_FCY_HGR_HST_LOW_FCY.SRC_DL AS SRC_DL,
            	MOV_FCY_HGR_HST_LOW_FCY.DATA_DT AS DATA_DT,
            	MOV_FCY_HGR_HST_LOW_FCY.SYS_VLD_FROM_TMS AS SYS_VLD_FROM_TMS,
            	MOV_FCY_HGR_HST_LOW_FCY.SYS_VLD_TO_TMS AS SYS_VLD_TO_TMS,
            	MOV_FCY_HGR_HST_LOW_FCY.SRC_STM_ID AS SRC_STM_ID,
            	MOV_FCY_HGR_HST_LOW_FCY.FCY_ID AS FCY_ID,
            	MOV_FCY_HGR_HST_LOW_FCY.FCY_RK AS FCY_RK,
            	MOV_FCY_HGR_HST_LOW_FCY.AR_ID AS AR_ID,
            	MOV_FCY_HGR_HST_LOW_FCY.FCY_AR_TP AS FCY_AR_TP,
            	MOV_FCY_HGR_HST_LOW_FCY.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_FCY_HGR_HST_LOW_FCY.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_FCY_HGR_HST_LOW_FCY.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_FCY_HGR_HST_LOW_FCY.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_FCY_HGR_HST_LOW_FCY.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_FCY_HGR_HST_LOW_FCY.UNDRL_AR_ID AS UNDRL_AR_ID
        FROM
            {{ ref('mov_fcy_hgr_hst_low_fcy') }} AS MOV_FCY_HGR_HST_LOW_FCY
        ORDER BY
            SRC_DL ASC,
            HIGHER_FCY_ID ASC 
)

SELECT * FROM mov_srt_hgr_hst_fcy

