
{{config(
  materialized='ephemeral'
)}}

WITH mov_fcy_hgr_hst_low_fcy AS (
SELECT
            		MOV_SRT_FCY_SPSDG_DRV_SPSDG_FCY_DT AS SPSDG_FCY_DT,
            	MOV_SRT_FCY_SPSDG_DRV_SPSDG_FCY_RK AS SPSDG_FCY_RK,
            	MOV_SRT_AR_X_AR_R_HGR_HIGHER_FCY_ID AS HIGHER_FCY_ID,
            	MOV_SRT_AR_X_AR_R_HGR_HIGHEST_FCY_ID AS HIGHEST_FCY_ID,
            	MOV_SRT_AR_X_AR_R_HGR_LEAF AS LEAF,
            	MOV_SRT_FCY_SPSDG_DRV_SRC_DL AS SRC_DL,
            	MOV_SRT_FCY_SPSDG_DRV_DATA_DT AS DATA_DT,
            	MOV_SRT_FCY_SPSDG_DRV_SYS_VLD_FROM_TMS AS SYS_VLD_FROM_TMS,
            	MOV_SRT_FCY_SPSDG_DRV_SYS_VLD_TO_TMS AS SYS_VLD_TO_TMS,
            	MOV_SRT_FCY_SPSDG_DRV_SRC_STM_ID AS SRC_STM_ID,
            	MOV_SRT_FCY_SPSDG_DRV_FCY_ID AS FCY_ID,
            	MOV_SRT_FCY_SPSDG_DRV_FCY_RK AS FCY_RK,
            	MOV_SRT_FCY_SPSDG_DRV_AR_ID AS AR_ID,
            	MOV_SRT_FCY_SPSDG_DRV_FCY_AR_TP AS FCY_AR_TP,
            	MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_DRV_OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	MOV_SRT_FCY_SPSDG_DRV_COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	MOV_SRT_FCY_SPSDG_DRV_CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	MOV_SRT_FCY_SPSDG_DRV_UNDRL_AR_ID AS UNDRL_AR_ID
        FROM
            {{ ref('jno_fcy_hgr_hst_low_fcy') }} AS JNO_FCY_HGR_HST_LOW_FCY 
)

SELECT * FROM mov_fcy_hgr_hst_low_fcy

