
{{config(
  materialized='ephemeral'
)}}

WITH mov_srt_fcy_ip_jcl_ev AS (
SELECT
            		REA_FCYAR_IP_JCL_EV.SRC_DL AS SRC_DL,
            	REA_FCYAR_IP_JCL_EV.DATA_DT AS DATA_DT,
            	REA_FCYAR_IP_JCL_EV.VLD_FROM_TMS AS SYS_VLD_FROM_TMS,
            	REA_FCYAR_IP_JCL_EV.VLD_TO_TMS AS SYS_VLD_TO_TMS,
            	REA_FCYAR_IP_JCL_EV.SRC_STM_ID AS SRC_STM_ID,
            	REA_FCYAR_IP_JCL_EV.FCY_ID AS FCY_ID,
            	REA_FCYAR_IP_JCL_EV.FCY_RK AS FCY_RK,
            	REA_FCYAR_IP_JCL_EV.AR_ID AS AR_ID,
            	REA_FCYAR_IP_JCL_EV.FCY_AR_TP AS FCY_AR_TP,
            	REA_FCYAR_IP_JCL_EV.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
            	REA_FCYAR_IP_JCL_EV.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
            	REA_FCYAR_IP_JCL_EV.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
            	REA_FCYAR_IP_JCL_EV.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
            	REA_FCYAR_IP_JCL_EV.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
            	REA_FCYAR_IP_JCL_EV.UNDRL_AR_ID AS UNDRL_AR_ID
        FROM
            {{ ref('rea_fcyar_ip_jcl_ev') }} AS REA_FCYAR_IP_JCL_EV
        ORDER BY
            SRC_DL ASC,
            AR_ID ASC 
)

SELECT * FROM mov_srt_fcy_ip_jcl_ev

