
{{config(
  materialized='ephemeral'
)}}

WITH mov_mdm_fcy_all_cols AS (
SELECT
    MOV_FCY_AR_IDENTN.DATA_DT AS DATA_DT,
    MOV_FCY_AR_IDENTN.FCY_ID AS FCY_ID,
    MOV_FCY_AR_IDENTN.SRC_STM_ID AS SRC_STM_ID,
    MOV_FCY_AR_IDENTN.SYS_VLD_FROM_TMS AS DATE_FROM,
    MOV_FCY_AR_IDENTN.UNDRL_AR_ID AS AR_ID,
    MOV_FCY_AR_IDENTN.SYS_VLD_TO_TMS AS DATE_TO,
    MOV_FCY_AR_IDENTN.SRC_DL AS SRC_DL,
    MOV_FCY_AR_IDENTN.FCY_RK AS FCY_RK,
    MOV_FCY_AR_IDENTN.FCY_AR_TP AS FCY_AR_TP,
    CASE
        WHEN MOV_FCY_AR_IDENTN.HIGHER_FCY_RK IS NULL THEN MOV_FCY_AR_IDENTN.FCY_RK
        ELSE MOV_FCY_AR_IDENTN.HIGHER_FCY_RK
    END AS HIGHER_FCY_RK,
    CASE
        WHEN MOV_FCY_AR_IDENTN.HIGHEST_FCY_RK IS NULL THEN MOV_FCY_AR_IDENTN.FCY_RK
        ELSE MOV_FCY_AR_IDENTN.HIGHEST_FCY_RK
    END AS HIGHEST_FCY_RK,
    CASE
        WHEN (MOV_FCY_AR_IDENTN.HLEAF = 1) THEN 'Y'
        WHEN (MOV_FCY_AR_IDENTN.HLEAF = 0) THEN 'N'
        WHEN (MOV_FCY_AR_IDENTN.HIGHEST_FCY_IN_HRY = "Y") THEN 'N'
        ELSE 'Y'
    END AS LOWEST_LVL_IND,
    MOV_FCY_AR_IDENTN.SPSDG_FCY_RK AS SPSDG_FCY_RK,
    MOV_FCY_AR_IDENTN.COURT_CTRLD_WRKOUT_FILL_DT AS COURT_CTRLD_WRKOUT_FILL_DT,
    MOV_FCY_AR_IDENTN.COURT_CTRLD_WRKOUT_FCY AS COURT_CTRLD_WRKOUT_FCY,
    MOV_FCY_AR_IDENTN.OUT_OF_COURT_WRKOUT_FCY AS OUT_OF_COURT_WRKOUT_FCY,
    MOV_FCY_AR_IDENTN.SPSDG_FCY_DT AS SPSDG_FCY_DT,
    MOV_FCY_AR_IDENTN.COURT_CTRLD_WRKOUT_CLS_DT AS COURT_CTRLD_WRKOUT_CLS_DT,
    MOV_FCY_AR_IDENTN.CR_OBLG_DFLTD AS CR_OBLG_DFLTD,
    MOV_FCY_AR_IDENTN.AR_IDENTN_NM AS FCY_VORTEX_ID,
    TIMESTAMP('{{ run_started_at }}') AS SYS_INRT_TMS
FROM
    {{ ref('mov_fcy_ar_identn') }} AS MOV_FCY_AR_IDENTN
)

SELECT * FROM mov_mdm_fcy_all_cols

