
{{ config(
 materialized='table',
 post_hook="
 INSERT INTO
    {{ source('DM_MPSCR', 'EWM_MDM_STAGE_FACILITY') }}
(DATA_DT,
FCY_ID,
SRC_STM_ID,
DATE_FROM,
AR_ID,
DATE_TO,
SRC_DL,
FCY_RK,
FCY_AR_TP,
HIGHER_FCY_RK,
HIGHEST_FCY_RK,
LOWEST_LVL_IND,
SPSDG_FCY_RK,
COURT_CTRLD_WRKOUT_FILL_DT,
COURT_CTRLD_WRKOUT_FCY,
OUT_OF_COURT_WRKOUT_FCY,
SPSDG_FCY_DT,
COURT_CTRLD_WRKOUT_CLS_DT,
CR_OBLG_DFLTD,
FCY_VORTEX_ID,
SYS_INRT_TMS)
                                                        SELECT DATA_DT,
FCY_ID,
SRC_STM_ID,
DATE_FROM,
AR_ID,
DATE_TO,
SRC_DL,
FCY_RK,
FCY_AR_TP,
HIGHER_FCY_RK,
HIGHEST_FCY_RK,
LOWEST_LVL_IND,
SPSDG_FCY_RK,
COURT_CTRLD_WRKOUT_FILL_DT,
COURT_CTRLD_WRKOUT_FCY,
OUT_OF_COURT_WRKOUT_FCY,
SPSDG_FCY_DT,
COURT_CTRLD_WRKOUT_CLS_DT,
CR_OBLG_DFLTD,
FCY_VORTEX_ID,
SYS_INRT_TMS
FROM
    {{ ref('mov_mdm_fcy_all_cols') }}
 "
)}}

SELECT 1 AS dummy_column

